<?php
/**
 * @var string $user the logged in user, if any
 * @var callable $pathFor function to resolve router paths
 * @var callable $srcUrlFor function to resolve resources
 *
 * @var array $experiments all experiments (Experiment)
 * @var array $detectors detectors (Detector) with results per experiment
 * @var Experiment $experiment the selected experiment, if any
 * @var Detector $detector the selected detector, if any
 */
use MuBench\ReviewSite\Models\Detector;
use MuBench\ReviewSite\Models\Experiment;

?>
<html>
    <head>
        <title>MUBench Review Site</title>
        <link rel="stylesheet" type="text/css" href="<?= $srcUrlFor('css/style.css') ?>" />
    </head>
    <body>
        <?php include "includes/menu.phtml" ?>

        <h1>Experiments</h1>

        <ul id="experiments">
        <?php foreach($experiments as $experiment) : ?>
            <li><span>Experiment <?= $experiment->id ?>: <?= htmlspecialchars($experiment->name) ?></span>
                <ul>
                <?php if ($detectors[$experiment->id]): ?>
                    <?php foreach ($detectors[$experiment->id] as $detector): ?>
                        <li><a href="<?= $pathFor('experiment.detector', ['experiment_id' => $experiment->id, 'detector_muid' => $detector->muid]) ?>"><?= $detector->muid ?></a></li>
                    <?php endforeach ?>
                <?php else: ?>
                    <li>No Results</li>
                <?php endif ?>
                </ul>
            </li>
        <?php endforeach; ?>
        </ul>
    </body>
</html>
