<?php
/**
 * @var string $user the logged in user, if any
 * @var callable $pathFor function to resolve router paths
 * @var callable $srcUrlFor function to resolve resources
 * @var callable $detectorName function to resolve detector names if blinded
 * @var callable $detectorPathId function to return detector id if blinded
 * @var array $experiments all experiments (Experiment)
 * @var array $detectors detectors (Detector) with results per experiment
 * @var Experiment $experiment the selected experiment, if any
 * @var Detector $detector the selected detector, if any
 */

use MuBench\ReviewSite\Models\Detector;
use MuBench\ReviewSite\Models\Experiment;

?>
<html>
    <head>
        <title>MUBench Review Site</title>
        <link rel="stylesheet" type="text/css" href="<?= $srcUrlFor('css/style.css') ?>" />
        <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    </head>
    <body>
        <?php include "includes/menu.phtml" ?>

        <h1>Experiments</h1>

        <ul id="experiments">
        <?php foreach($experiments as $experiment) : ?>
            <li><span>Experiment <?= $experiment->id ?>: <?= htmlspecialchars($experiment->name) ?></span>
                <table class="invisible">
                <tr>
                    <th></th>
                    <th></th>
                </tr>
                <?php if ($detectors[$experiment->id]): ?>
                    <?php foreach ($detectors[$experiment->id] as $detector): ?>
                        <tr>
                            <td>
                                <a href="<?= $pathFor('experiment.detector', ['experiment_id' => $experiment->id, 'detector_muid' => $detectorPathId($detector)]) ?>"><?= $detectorName($detector->muid) ?></a>
                            </td>
                            <td>
                                <?php if($user) : ?>
                                    <?php include "includes/detector_review_state.phtml" ?>
                                <?php endif; ?>
                            </td>
                        </tr>
                    <?php endforeach ?>
                <?php else: ?>
                    <tr><td>No Results</td></tr>
                <?php endif ?>
                </table>
            </li>
        <?php endforeach; ?>
        </ul>
    </body>
</html>
