<?php
/**
 * @var string $user the logged in user, if any
 *
 * @var string $site_base_url
 * @var string $public_url_prefix
 * @var string $private_url_prefix
 * @var string $url_prefix the public or private url prefix, depending on whether the user is logged in
 *
 * @var string $path the current route path
 * @var string $origin_param url parameter that carries the $path
 * @var string $origin_path referrer path
 *
 * @var array $experiments all experiments (Experiment)
 * @var array $detectors detectors (Detector) with results per experiment
 * @var array $misuses the misuses reviewed by the current user, indexed by experiment id and detector name
 */
use MuBench\ReviewSite\Model\Decision;
use MuBench\ReviewSite\Model\ReviewState;

?>
<html>
<head>
    <title>MuBench :: Review Site</title>
    <link rel="stylesheet" type="text/css" href="<?= $site_base_url ?>style/style.css" />
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
<?php include "includes/menu.phtml"; ?>

<?php foreach($misuses as $experiment => $detectors) : ?>
<h1>Experiment: <?= htmlspecialchars($experiment); ?></h1>
<table>
    <thead>
    <tr>
        <th>Project</th>
        <th>Version</th>
        <th>Misuse</th>
        <th>Decision</th>
        <th>Reviews</th>
        <th>Your Review</th>
        <th>Your Comment</th>
    </tr>
    </thead>
    <tbody>
    <?php $last_project = ""; $version = "" ?>
    <?php foreach($detectors as $detector => $misuses) : ?>
    <?php foreach($misuses as $misuse) : /** @var \MuBench\ReviewSite\Model\Misuse $misuse */ ?>
        <?php
        $project = $misuse->getProject();
        $new_project = strcmp($last_project, $misuse->getProject()) !== 0;
        $last_project = $project;
        $new_version = strcmp($version, $misuse->getVersion()) !== 0;
        $version = $misuse->getVersion();
        ?>
            <?php
            $classes = [];
            if($new_project) $classes[] = "top";
            $style_classes = implode(" ", $classes);
            ?>
            <tr>
                <td class="<?= $style_classes ?>">
                    <?= $new_project ? htmlspecialchars($project) : ""; ?></td>
                <td class="<?= $style_classes ?>">
                    <?= $new_version ? htmlspecialchars($version) : ""; ?></td>
                <td class="<?= $style_classes ?>">
                    <?= htmlspecialchars($misuse->getShortId()); ?></td>
                <?php
                $review_url = $url_prefix . htmlspecialchars($experiment) . "/" . htmlspecialchars($detector) . "/" .
                    htmlspecialchars($project) . "/" . htmlspecialchars($version) . "/" . htmlspecialchars($misuse->id);
                ?>
                <td class="<?= $style_classes ?>">
                    <?php $review_state = $misuse->getReviewState() ?>
                    <?php if ($review_state == ReviewState::NOTHING_TO_REVIEW): ?>
                    <?php elseif ($review_state == ReviewState::NEEDS_REVIEW): ?>
                        <i class="fa fa-search" aria-hidden="true" style="color:red;" title="Needs Review"></i>
                    <?php elseif ($review_state == ReviewState::NEEDS_CLARIFICATION): ?>
                        <i class="fa fa-question-circle" aria-hidden="true" style="color:blue;" title="Needs Clarification"></i>
                    <?php elseif ($review_state == ReviewState::DISAGREEMENT): ?>
                        <a href="<?= $review_url ?>/resolution<?= $origin_param ?>"><i class="fa fa-exclamation-triangle" aria-hidden="true" style="color:red;" title="Disagreement"></i></a>
                    <?php elseif ($review_state == ReviewState::AGREEMENT_YES): ?>
                        <i class="fa fa-thumbs-o-up" aria-hidden="true" style="color:green;" title="Agreement: Yes"></i>
                    <?php elseif ($review_state == ReviewState::AGREEMENT_NO): ?>
                        <i class="fa fa-thumbs-o-down" aria-hidden="true" style="color:darkred;" title="Agreement: No"></i>
                    <?php elseif ($review_state == ReviewState::RESOLVED_YES): ?>
                        <i class="fa fa-thumbs-o-up" aria-hidden="true" style="color:green;" title="Resolved: Yes"></i>
                        (<a href="<?= $review_url ?>/resolution<?= $origin_param ?>"><i class="fa fa-handshake-o" aria-hidden="true" title="Resolution"></i></a>)
                    <?php elseif ($review_state == ReviewState::RESOLVED_NO): ?>
                        <i class="fa fa-thumbs-o-down" aria-hidden="true" style="color:darkred;" title="Resolved: No"></i>
                        (<a href="<?= $review_url ?>/resolution<?= $origin_param ?>"><i class="fa fa-handshake-o" aria-hidden="true" title="Resolution"></i></a>)
                    <?php endif; ?>
                </td>
                <td class="<?= $style_classes ?>">
                    <ul class="inline">
                        <?php foreach($misuse->getReviews() as $review) : /** @var \MuBench\ReviewSite\Model\Review $review */ ?>
                            <?php $reviewer_name = htmlspecialchars($review->getReviewerName()) ?>
                            <?php if(strcmp($reviewer_name, $user) !== 0) : ?>
                                <li style="display:inline"><a href="<?= $review_url ?>/<?= $reviewer_name ?>"><?= $reviewer_name ?></a></li>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </ul>
                </td>
                <td class="<?= $style_classes ?>">
                    <a href="<?= $review_url ?><?= $origin_param ?>" class="button">edit
                        <?php $your_decision = $misuse->getReview($user)->getDecision() ?>
                        <?php if ($your_decision == Decision::YES): ?>
                            (<i class="fa fa-thumbs-o-up" aria-hidden="true" style="color:green;" title="Yes"></i>)
                        <?php elseif ($your_decision == Decision::NO): ?>
                            (<i class="fa fa-thumbs-o-down" aria-hidden="true" style="color:darkred;" title="No"></i>)
                        <?php else: ?>
                            (<i class="fa fa-question-circle" aria-hidden="true" style="color:blue;" title="Need Clarification"></i>)
                        <?php endif; ?>
                    </a>
                </td>
                <td class="<?= $style_classes ?>" style="max-width: 300px;">
                    <?= $misuse->getReview($user)->getComment() ?>
                </td>
            </tr>
            <?php
            $new_version = false;
            $new_project = false;
            ?>
        <?php endforeach; ?>
        <?php endforeach; ?>
    </tbody>
</table>
<?php endforeach; ?>
</body>
</html>
