<?php
/**
 * @var string $user the logged in user, if any
 *
 * @var string $site_base_url
 * @var string $public_url_prefix
 * @var string $private_url_prefix
 * @var string $api_url_prefix
 * @var string $uploads_url_prefix
 * @var string $url_prefix the public or private url prefix, depending on whether the user is logged in
 * @var string $uploads_path
 *
 * @var string $path the current route path
 * @var string $origin_param url parameter that carries the $path
 * @var string $origin_path referrer path
 *
 * @var array $experiments all experiments (Experiment)
 * @var array $detectors detectors (Detector) with results per experiment
 * @var Experiment $experiment the selected experiment, if any
 * @var Detector $detector the selected detector, if any
 *
 * @var Parsedown $markdown_parser markdown parser
 *
 * @var \MuBench\ReviewSite\Models\Misuse $misuse
 * @var \MuBench\ReviewSite\Models\Misuse $next_misuse
 * @var \MuBench\ReviewSite\Models\Misuse $next_reviewable_misuse
 * @var \MuBench\ReviewSite\Models\Misuse $previous_misuse
 * @var \MuBench\ReviewSite\Models\Review $review
 * @var bool $is_reviewer whether the user is the author of this review
 * @var array $violations all violations of this misuse in exp1/3, all possible violations in exp2
 */

use MuBench\ReviewSite\Models\Detector;
use MuBench\ReviewSite\Models\Experiment;

$columns_to_ignore = array(
        "target_snippets",
        "file",
        "method",
        "line",
        "project",
        "version",
        "misuse",
        "identifier",
        "rank",
        "exp",
        "startline",
        "created_at",
        "id",
        "misuse_muid",
        "misuse_id",
        "updated_at",
        "project_muid",
        "version_muid",
        "experiment_id"
    );
$origin_path = $origin_path ? $origin_path : $pathFor('experiment.detector', array("experiment_id"=> $experiment->id, "detector_muid" => $detector->muid));

?>
        <html>
            <head>
                <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
                <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
                <link rel="stylesheet" type="text/css" href="<?= $site_base_url ?>css/style.css" />

                <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
                <script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js?autoload=true&amp;skin=sunburst"></script>
                <script src="http://cdn.rawgit.com/ariutta/svg-pan-zoom/master/dist/svg-pan-zoom.min.js"></script>
                <style>
                    .prettyprint li:before {
                        content: "    ";
                        border-radius: 25%;
                        padding: 0 2px;
                        color: white;
                    }
                    <?php foreach($misuse->findings as $hit) : ?>
                        <?php if($hit->startline) : ?>
                            <?php foreach($misuse->snippets() as $snippet) : ?>
                                    #code_<?= htmlspecialchars($snippet->id)?> li:nth-child(<?= htmlspecialchars(abs($snippet->line - $hit->startline - 1)); ?>):before {
                                        content: "<?= str_pad($hit->rank, 4, " ", STR_PAD_LEFT) ?>";
                                        background-color: red;
                                    }
                            <?php endforeach; ?>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </style>
            </head>
            <body style="margin-bottom:30px;">
            <?php include "includes/menu.phtml" ?>
        <h1>Review</h1>
        <table class="invisible">
            <tr><td><b>Detector:</b></td><td><?= htmlspecialchars($detector->muid); ?></td></tr>
            <tr><td><b>Target:</b></td><td>project '<?= $markdown_parser->text($misuse->getProject()); ?>' version <?= $markdown_parser->text($misuse->getVersion()); ?></td></tr>
            <?php if($experiment->id !== 2) : ?>
                <tr><td><b>Misuse:</b></td><td>misuse '<?= $markdown_parser->text($misuse->misuse_muid); ?>'</td></tr>
            <?php endif; ?>
            <?php if($user || $misuse->misuse_tags) : ?>
                <tr>
                <td><b>Tags:</b></td>
                <td>
                    <?php if($misuse->misuse_tags): ?>
                        <?php foreach($misuse->misuse_tags as $tag) : ?>
                            <div class="misuse-tag" style="background-color:<?= htmlspecialchars($tag->color) ?>;color:<?= htmlspecialchars($tag->getFontColor()) ?>;">
                                <span><?= htmlspecialchars($tag->name) ?></span>
                                <?php if($user) : ?>
                                <div style="display:inline-block;padding-right:2px;margin:0;color:black">
                                    <form action="<?= $pathFor('tag.remove', array('experiment_id' => $experiment->id, 'detector_muid' => $detector->muid, 'project_muid' => $misuse->getProject(), 'version_muid' => $misuse->getVersion(), 'misuse_muid' => $misuse->misuse_muid, 'tag_id' => $tag->id)) ?>" method="post" target="">
                                        <input type="hidden" name="path" value="<?= htmlspecialchars($path . "?origin=" . $origin_path); ?>">
                                        <input type="hidden" name="misuse_id" value="<?= htmlspecialchars($misuse->id); ?>">
                                        <button style="border:none;outline:none;background-color:<?= htmlspecialchars($tag->color) ?>;margin:0;padding:0" type="submit"><i class="fa fa-trash"></i></button>
                                    </form>
                                </div>
                                <?php endif; ?>
                            </div>
                        <?php endforeach; ?>
                    <?php endif; ?>
                    <?php if($user) : ?>
                            <div style="display:inline-block;height:100%;padding:4px;">
                                <form id="tag-form" action="<?= $pathFor('tag.add', array('experiment_id' => $experiment->id, 'detector_muid' => $detector->muid, 'project_muid' => $misuse->getProject(), 'version_muid' => $misuse->getVersion(), 'misuse_muid' => $misuse->misuse_muid)) ?>" method="post" target="">
                                    <input type="hidden" name="misuse_id" value="<?= htmlspecialchars($misuse->id); ?>">
                                    <input type="hidden" name="path" value="<?= htmlspecialchars($path . "?origin=" . $origin_path); ?>">
                                    <input id="tag-input" class="tag-input" maxlength="100" list="tags" name="tag_name" placeholder="add new tag" autocomplete="off">
                                    <datalist id="tags">
                                        <?php foreach($tags as $tag) : ?>
                                            <option value="<?= htmlspecialchars($tag->name); ?>">
                                        <?php endforeach;?>
                                    </datalist>
                                </form>
                            </div>
                        <?php endif; ?>
                </td>
                </tr>
            <?php endif; ?>
        </table>
        <?php if($experiment->id !== 2) : ?>
            <h2>Misuse Details</h2>
            <p>Details about the known misuse from the MUBench dataset.</p>
        <?php else : ?>
            <h2>Potential Misuse</h2>
            <p>Anomaly identified by the detector. Please review whether this anomaly corresponds to a misuse.</p>
        <?php endif; ?>
        <table class="invisible fw">
        <?php if($experiment->id !== 2) : ?>
            <tr><td class="vtop"><b>Description:</b></td><td><?= $markdown_parser->text($misuse->metadata->description); ?></td></tr>
            <tr>
                <td class="vtop"><b>Fix Description:</b></td>
                <td><?= $markdown_parser->text($misuse->metadata->fix_description); ?>
                    <?php if ($misuse->metadata->diff_url): ?>(<a href="<?= $misuse->metadata->diff_url; ?>">see diff</a>)<?php endif ?>
                </td></tr>
            <tr><td class="vtop"><b>Violations:</b></td><td>
            <ul>
            <?php if($misuse->hasViolations()) : ?>
            <?php foreach($misuse->getViolations() as $v) : ?>
                <li><?= htmlspecialchars($v->name); ?></li>
            <?php endforeach; ?>
            <?php endif; ?>
            </ul></td></tr>
        <?php else : ?>
            <tr><td><b>Finding:</b></td><td><?= $markdown_parser->text($misuse->misuse_muid); ?></td></tr>
        <?php endif; ?>
            <tr><td><b>In File:</b></td><td><?= $markdown_parser->text($misuse->getFile()); ?></td></tr>
            <tr><td><b>In Method:</b></td><td><?= $markdown_parser->text($misuse->getMethod()); ?></td></tr>
            <tr>
            <?php if($experiment->id !== 2) : ?>
                <td class="vtop"><b>Code with Misuse:</b></td>
            <?php else : ?>
                <td class="vtop"><b>Code with Finding:</b></td>
            <?php endif; ?>
            <td>
                <?php if($misuse->hasSnippets()) : ?>
                    <?php $delete_snippets_enabled = (sizeof($misuse->snippets()) >= 2 && $user); ?>
                    <?php foreach($misuse->snippets() as $snippet): ?>
                        <?php if($delete_snippets_enabled): ?>
                            <form id="delete_snippet_form" action="<?= $pathFor('snippet.remove', array('experiment_id' => $experiment->id, 'detector_muid' => $detector->muid, 'project_muid' => $misuse->getProject(), 'version_muid' => $misuse->getVersion(), 'misuse_muid' => $misuse->misuse_muid, 'snippet_id' => $snippet->id)) ?><?= $origin_param ?>" method="POST" target="">
                                <input type="hidden" name="path" value="<?= htmlspecialchars($path . "?origin=" . $origin_path); ?>">
                                <button style="border:none;background-color:white;position:absolute;right:5px" type="submit"><i class="fa fa-trash"></i></button>
                            </form>
                        <?php endif; ?>
                        <pre id="code_<?= htmlspecialchars($snippet->id); ?>" class="prettyprint linenums:<?= htmlspecialchars($snippet->line); ?>"><code class="language-java"><?= htmlspecialchars($snippet->snippet); ?></code></pre>
                    <?php endforeach; ?>
                <?php else : ?>
                    <pre class="prettyprint"><code class="language-java">code not found</code></pre>
                    <?php if($user) : ?>
                        <input class="button" type="button" onclick="show(this);" value="Add code snippet">
                        <form  id="snippet_form" style="display:none;" action="<?= $pathFor('snippet.add', array('experiment_id' => $experiment->id, 'detector_muid' => $detector->muid, 'project_muid' => $misuse->getProject(), 'version_muid' => $misuse->getVersion(), 'misuse_muid' => $misuse->misuse_muid)) ?>" method="post" target="">
                            <table>
                            <tr>
                                <td>
                                    <label>Line:
                                        <input type="number" name="line">
                                    </label>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <input type="hidden" name="misuse_id" value="<?= htmlspecialchars($misuse->id); ?>">
                                    <input type="hidden" name="path" value="<?= htmlspecialchars($path . "?origin=" . $origin_path); ?>">
                                    <textarea name="snippet" title="Code Snippet" cols="80" rows="5"></textarea>
                                </td>
                            </tr>
                            <tr>
                                <td><input class="button" type="submit" value="Save snippet" /></td>
                            </tr>
                            </table>
                        </form>
                    <?php endif; ?>
                <?php endif; ?>
            </td></tr>
            <?php if($experiment->id === 1) : ?>
                    <tr><td class="vtop"><b>Correct Usage:</b></td>
                        <td>
                <?php foreach($misuse->metadata->correct_usages as $correctUsage) : ?>
                    <pre class="prettyprint"><code class="language-java"><?= htmlspecialchars($correctUsage->code); ?></code></pre>
                <?php endforeach; ?>
                        </td></tr>
            <?php endif; ?>
        </table>
            <?php if($reviewer && $is_reviewer): ?>
                <form id="review_form" action="<?= $pathFor('update.review', array('experiment_id' => $experiment->id, 'detector_muid' => $detector->muid, 'project_muid' => $misuse->getProject(), 'version_muid' => $misuse->getVersion(), 'misuse_muid' => $misuse->misuse_muid, 'reviewer_name' => $reviewer->name), true) ?>" method="post" target="">
            <?php endif; ?>
            <?php if($misuse->hasPotentialHits()) : ?>

            <?php if($experiment->id !== 2) : ?>
            <h2>Potential Hits</h2>
            <p>Findings of the detector that identify an anomaly in the same file and method as the known misuse.</p>
        <?php else : ?>
            <h2>Metadata</h2>
        <?php endif; ?>
        <table class="potential_hits">
            <?php

            function escape_detector_special($detector_value)
            {
                return str_replace(['<init>', '<clinit>'], ['&lt;init&gt;', '&lt;clinit&gt;'], $detector_value);
            }

            /**
             * @param string $property the property to check for
             * @param array $potential_hits the potential hits to check
             * @return bool true if none of the potential hits has a value for the property, false otherwise
             */
            function is_empty($property, $potential_hits)
            {
                return array_reduce($potential_hits, function ($carry, $potential_hit) use ($property) {
                    return $carry && empty($potential_hit[$property]);
                }, true);
            }
            $potential_hits = $misuse->findings;
            $columns = array_filter(array_keys(current($potential_hits->toArray())), function ($key) use ($columns_to_ignore, $potential_hits) {
                return !in_array($key, $columns_to_ignore) && !is_empty($key, $potential_hits->toArray());
            });

            sort($columns);
            ?>

        <tr>
            <th>Hit</th>
            <th>Rank</th>
            <?php foreach($columns as $column) : ?>
                <th><?= htmlspecialchars(ucwords(str_replace("_", " ", $column))); ?></th>
            <?php endforeach; ?>
            <?php if($experiment->id === 2) : ?>
                <th>Violations</th>
            <?php endif; ?>
        </tr>

        <?php foreach($potential_hits as $hit) : ?>
        <tr>
            <td>
            <?php if($user && $is_reviewer) : ?>
                <select name="review_hit[<?= htmlspecialchars($hit['rank']); ?>][hit]" title="Decision" size="1" >
                    <?php if($review && strcmp($review->getHitDecision($hit['rank']), "No") === 0) : ?>
                        <option selected="selected" value="No" >No</option>
                    <?php else : ?>
                        <option value="No" >No</option>
                    <?php endif;?>
                    <?php if($review && strcmp($review->getHitDecision($hit['rank']), "Yes") === 0) : ?>
                    <option selected="selected" value="Yes" >Yes</option>
                    <?php else : ?>
                    <option value="Yes" >Yes</option>
                    <?php endif;?>
                    <?php if($review && strcmp($review->getHitDecision($hit['rank']), "?") === 0) : ?>
                        <option selected="selected" value="?" >?</option>
                    <?php else : ?>
                        <option value="?" >?</option>
                    <?php endif;?>
                </select>
            <?php elseif($review) : ?>
                <?php if(!$review->getHitDecision($hit->rank)) : ?>
                    No
                <?php else : ?>
                    <?= htmlspecialchars($review->getHitDecision($hit->rank)); ?>
                <?php endif; ?>
            <?php elseif($user) : ?>
                No
            <?php else : ?>
                ?
            <?php endif;?>
            </td>
            <td>
                <?= $markdown_parser->text($hit->rank); ?>
            </td>
            <?php foreach($columns as $column) : ?>
            <td>
                <?php if(strlen($hit[$column]) > 4 && substr($hit[$column], -4) === ".svg") : ?>
                    <?php
                        $object_id = $column . $hit['rank'];

                        $svg_rel_path = "{$experiment->id}/{$detector->id}/{$misuse->getProject()}/{$misuse->getVersion()}/{$hit[$column]}";
                        // obtain SVG view size
                        try {
                            $xmlget = simplexml_load_file("{$uploads_path}/{$svg_rel_path}");
                            $xmlattributes = $xmlget->attributes();
                            $svg_width = (string)$xmlattributes->width;
                            $svg_height = (string)$xmlattributes->height;
                        } catch (Exception $e) {
                            $svg_width = "700px";
                            $svg_height = "700px";
                        }
                    ?>
                    <object id="<?= $object_id ?>" type="image/svg+xml" data="<?= "{$uploads_url_prefix}/{$svg_rel_path}" ?>" style="width: <?= $svg_width ?>; height: <?= $svg_height ?>; max-width: 700pt; max-height: 700pt;"></object>
                    <script>
                        document.getElementById("<?= $object_id ?>").onload = function() {
                            svgPanZoom("#<?= $object_id ?>", {
                                zoomEnabled: true
                            });
                        };
                    </script>
                <?php elseif(strlen($hit[$column]) > 4 && substr($hit[$column], -4) === ".png") : ?>
                    <img src="<?= "{$uploads_url_prefix}/{$experiment->id}/{$detector->id}/{$misuse->getProject()}/{$misuse->getVersion()}/{$hit[$column]}" ?>" />
                <?php else : ?>
                    <?= $markdown_parser->text(escape_detector_special($hit[$column])); ?>
                <?php endif; ?>
            </td>
            <?php endforeach; ?>
            <?php if($experiment->id === 2) : ?>
                <td>
                    <select name="review_hit[<?= htmlspecialchars($hit->rank); ?>][violations][]" title="Violations" size="<?= count($violations) ?>" multiple <?= ($user && $is_reviewer) ? "" : "disabled" ?>>
                        <?php foreach($violations as $violation) : ?>
                            <?php if($review && in_array($violation->id, array_column($review->getHitViolations($hit->rank), 'id'))) : ?>
                                    <option selected="selected" value="<?= $violation->id ?>"><?= htmlspecialchars($violation->name) ?></option>
                            <?php else: ?>
                                <option value="<?= $violation->id ?>"><?= htmlspecialchars($violation->name) ?></option>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </select>
                </td>
            <?php endif; ?>
        </tr>
       <?php endforeach; ?>
       </table>
        <?php endif; ?>
        <?php if($is_reviewer && $reviewer) :?>
                <input type="hidden" name="misuse_id" value="<?= htmlspecialchars($misuse->id); ?>">
                    <div id="comment-area" class="floating-comment" style="bottom:50px;right:10px">
                        <?php if($misuse->hasSufficientReviews() && $reviewer->name !== "resolution" && !$misuse->hasReviewed($reviewer)) : ?>
                            <div class="comment-overlay" id="overlay" style="z-index:2;"></div>
                            <div class="comment-overlay-button" id="overlay-button" style="z-index:3"><span>This misuse was already reviewed.</span><a class="button" onclick="review(this)">review it anyways</a></div>
                        <?php endif; ?>
                        <table class="invisible">
                            <tr><td id="review_area" colspan="2" style="visibility: visible">
                                    <?php if($review) : ?>
                                        <textarea id="review_comment" name="review_comment" cols="80" rows="5"><?= htmlspecialchars($review->comment); ?></textarea>
                                    <?php else : ?>
                                        <textarea id="review_comment" name="review_comment" cols="80" rows="5"></textarea>
                                    <?php endif; ?>
                                </td></tr>
                        </table>
                    </div>
            </form>
        <?php elseif($review && (!$user || !$is_reviewer)) :?>
                <table class="invisible">
                    <tr><td>Reviewer Name:</td>
                        <td><?= htmlspecialchars($review->reviewer->name); ?></td></tr>
                    <tr><td class="vtop"><label for="review_comment">Comment</label>:</td>
                        <td>
                            <?= $markdown_parser->text($review->comment); ?>
                        </td></tr>
                </table>
        <?php endif; ?>
            <div class="review-nav-bar">
                <?php
                $next_misuse_path = $next_misuse ? $pathFor('view', array('experiment_id' => $experiment->id, 'detector_muid' => $detector->muid, 'project_muid' => $next_misuse->getProject(), 'version_muid' => $next_misuse->getVersion(), 'misuse_muid' => $next_misuse->misuse_muid)) . "?origin=$origin_path" . ($experiment->id === 2 ? "&ex2_review_size=$ex2_review_size" : "") : "";
                $next_reviewable_misuse_path = $next_reviewable_misuse ? $pathFor('view', array('experiment_id' => $experiment->id, 'detector_muid' => $detector->muid, 'project_muid' => $next_reviewable_misuse->getProject(), 'version_muid' => $next_reviewable_misuse->getVersion(), 'misuse_muid' => $next_reviewable_misuse->misuse_muid)) . "?origin=$origin_path" . ($experiment->id === 2 ? "&ex2_review_size=$ex2_review_size" : "") : "";
                $previous_misuse_path = $previous_misuse ? $pathFor('view', array('experiment_id' => $experiment->id, 'detector_muid' => $detector->muid, 'project_muid' => $previous_misuse->getProject(), 'version_muid' => $previous_misuse->getVersion(), 'misuse_muid' => $previous_misuse->misuse_muid)) . "?origin=$origin_path" . ($experiment->id === 2 ? "&ex2_review_size=$ex2_review_size" : "") : "";
                ?>
                <a href="<?= $origin_path ?>" class="button">return</a>
                <a href="<?= $previous_misuse_path ?>" class="button <?= $previous_misuse_path ? "" :  "disabled" ?>"><</a>
                <?php if($reviewer && $is_reviewer): ?>
                    <div style="padding:0;margin:0;display:inline-block;left:38%;position:relative">
                        <a class="button" onclick="comment()">Comment</a>
                        <div class="dropdown">
                            <div id="save-dropdown" class="dropdown-content" style="margin-left:-5px;margin-bottom:-3px;padding:0;bottom:100%;">
                                <?php if($next_reviewable_misuse_path) : ?>
                                    <a onclick="saveReview('return')">Save and return</a>
                                <?php endif; ?>
                                <a onclick="saveReview('save')">Save</a>
                            </div>
                            <?php if($next_reviewable_misuse_path) : ?>
                                <a class="button" style="margin:-5px;min-width:120px;" onclick="saveReview('review')">Save and next misuse</a>
                            <?php else : ?>
                                <a class="button" style="margin:-5px;min-width:120px;" onclick="saveReview('return')">Save and return</a>
                            <?php endif; ?>
                            <a id="dropdown-button" class="button" style="padding:5px;"><i class="fa fa-angle-up"></i></a>
                        </div>
                    </div>
                <?php endif; ?>
                <div style="display:inline-block;float:right;margin-right:10px;">
                    <a href="<?= $next_misuse_path ?>" class="button <?= $next_misuse_path ? "" :  "disabled" ?>">></a>
                    <?php if($reviewer && $is_reviewer): ?>
                        <a href="<?= $next_reviewable_misuse_path ?>" class="button <?= $next_reviewable_misuse_path ? "" :  "disabled" ?>">>></a>
                    <?php endif; ?>
                </div>
            </div>

            <?php if($reviewer && $is_reviewer): ?>
                <script>
                    var origin = "<?= $origin_path ?>";
                    var next_review = "<?= $next_reviewable_misuse_path ?>";
                    var next_reviewable = <?= $next_reviewable_misuse_path ? 1 : 0 ?>;
                </script>
                <script src="<?= $site_base_url ?>js/nav-bar.js"></script>
                <script>
                    <?php if($review): ?>
                    // fix for https://github.com/sparksuite/simplemde-markdown-editor/issues/344
                    document.getElementById("comment-area").style.display="block";
                    simplemde.value("<?= $review->comment ?>");
                    simplemde.codemirror.refresh();
                    document.getElementById("comment-area").style.display="none";
                    <?php endif; ?>
                </script>
            <?php endif; ?>
            </body>
        </html>
    
