<?php
/**
 * @var string $user the logged in user, if any
 *
 * @var string $site_base_url
 * @var string $public_url_prefix
 * @var string $private_url_prefix
 * @var string $api_url_prefix
 * @var string $uploads_url_prefix
 * @var string $url_prefix the public or private url prefix, depending on whether the user is logged in
 *
 * @var string $path the current route path
 * @var string $origin_param url parameter that carries the $path
 * @var string $origin_path referrer path
 *
 * @var array $experiments all experiments (Experiment)
 * @var array $detectors detectors (Detector) with results per experiment
 * @var Experiment $experiment the selected experiment, if any
 * @var Detector $detector the selected detector, if any
 *
 * @var \MuBench\ReviewSite\Model\Misuse $misuse
 * @var \MuBench\ReviewSite\Model\Review $review
 * @var bool $is_reviewer whether the user is the author of this review
 */
use MuBench\ReviewSite\Model\Detector;
use MuBench\ReviewSite\Model\Experiment;

    $columns_to_ignore = array(
        "target_snippets",
        "file",
        "method",
        "line",
        "project",
        "version",
        "misuse",
        "identifier",
        "rank",
        "exp"
    );
?>
        <html>
            <head>
                <link rel="stylesheet" type="text/css" href="<?= $site_base_url ?>style/style.css" />
                <script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js?autoload=true&amp;skin=sunburst"></script>
            </head>
            <body>

            <?php include "includes/menu.phtml" ?>

        <h1>Review</h1>
        <table class="invisible">
            <tr><td><b>Detector:</b></td><td><?= htmlspecialchars($detector->name); ?></td></tr>
            <tr><td><b>Target:</b></td><td>project '<?= htmlspecialchars($misuse->getProject()); ?>' version <?= htmlspecialchars($misuse->getVersion()); ?></td></tr>
            <?php if($experiment->getId() !== "ex2") : ?>
                <tr><td><b>Misuse:</b></td><td>misuse '<?= htmlspecialchars($misuse->getShortId()); ?>'</td></tr>
            <?php endif; ?>
        </table>
        <?php if($experiment->getId() !== "ex2") : ?>
            <h2>Misuse Details</h2>
            <p>Details about the known misuse from the MUBench dataset.</p>
        <?php else : ?>
            <h2>Potential Misuse</h2>
            <p>Anomaly identified by the detector. Please review whether this anomaly corresponds to a misuse.</p>
        <?php endif; ?>
        <table class="invisible fw">
        <?php if($experiment->getId() !== "ex2") : ?>
            <tr><td class="vtop"><b>Description:</b></td><td><?= htmlspecialchars($misuse->getDescription()); ?></td></tr>
            <tr>
                <td class="vtop"><b>Fix Description:</b></td>
                <td><?= htmlspecialchars($misuse->getFixDescription()); ?>
                    <?php if ($misuse->hasDiff()): ?>(<a href="<?= htmlspecialchars($misuse->getDiff()); ?>">see diff</a>)<?php endif ?>
                </td></tr>
            <tr><td class="vtop"><b>Violation Types:</b></td><td>
            
            <ul>
            <?php if($misuse->hasViolationTypes()) : ?>
            <?php foreach($misuse->getViolationTypes() as $v) : ?>
                <li><?= htmlspecialchars($v); ?></li>
            <?php endforeach; ?>
        <?php endif; ?>
            </ul></td></tr>
        <?php else : ?>
            <tr><td><b>Finding:</b></td><td><?= htmlspecialchars($misuse->getShortId()); ?></td></tr>
        <?php endif; ?>
            <tr><td><b>In File:</b></td><td><?= htmlspecialchars($misuse->getFile()); ?></td></tr>
            <tr><td><b>In Method:</b></td><td><?= htmlspecialchars($misuse->getMethod()); ?></td></tr>
            <tr>
            <?php if($experiment->getId() !== "ex2") : ?>
                <td class="vtop"><b>Code with Misuse:</b></td>
            <?php else : ?>
                <td class="vtop"><b>Code with Finding:</b></td>
            <?php endif; ?>
            <td>
                <?php if($misuse->hasCode()) : ?>
                    <?php foreach($misuse->getCode() as $c): ?>
                    <pre class="prettyprint linenums:<?= htmlspecialchars($c['line']); ?>"><code class="language-java"><?= htmlspecialchars($c['snippet']); ?></code></pre>
                    <?php endforeach; ?>
                <?php elseif(!$misuse->hasCode()) : ?>
                    <pre class="prettyprint"><code class="language-java">code not found</code></pre>
                    <?php if($user) : ?>
                        <input type="button" onclick="show(this);" value="Add code snippet">
                        <form  id="snippet_form" style="display:none;" action="<?= $api_url_prefix ?>upload/snippet" method="post" target="">
                            <table>
                            <tr>
                                <td>
                                    <label>Line:
                                        <input type="number" name="line">
                                    </label>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <input type="hidden" name="exp" value="<?= htmlspecialchars($experiment->getId()); ?>">
                                    <input type="hidden" name="detector" value="<?= htmlspecialchars($detector->name); ?>">
                                    <input type="hidden" name="project" value="<?= htmlspecialchars($misuse->getProject()); ?>">
                                    <input type="hidden" name="version" value="<?= htmlspecialchars($misuse->getVersion()); ?>">
                                    <input type="hidden" name="misuse" value="<?= htmlspecialchars($misuse->id); ?>">
                                    <input type="hidden" name="path" value="<?= htmlspecialchars($path); ?>">
                                    <textarea name="snippet" title="Code Snippet" cols="80" rows="5"></textarea>
                                </td>
                            </tr>
                            <tr>
                                <td><input type="submit" value="Save snippet" /></td>
                            </tr>
                            </table>
                        </form>
                    <?php endif; ?>
                <?php endif; ?>
            </td></tr>
            <?php if($experiment->getId() === "ex1") : ?>
                    <tr><td class="vtop"><b>Code with Pattern(s):</b></td>
                        <td>
                <?php foreach($misuse->getPatterns() as $pattern) : ?>
                    <pre class="prettyprint"><code class="language-java"><?= htmlspecialchars($pattern["code"]); ?></code></pre>
                <?php endforeach; ?>
                        </td></tr>
            <?php endif; ?>
        </table>
            <form action="<?= "{$api_url_prefix}upload/review/{$experiment->getId()}/{$detector->name}" ?>" method="post" target="">
            <?php if($misuse->hasPotentialHits()) : ?>

            <?php if($experiment->getId() !== "ex2") : ?>
            <h2>Potential Hits</h2>
            <p>Findings of the detector that identify an anomaly in the same file and method as the known misuse.</p>
        <?php else : ?>
            <h2>Metadata</h2>
        <?php endif; ?>
        <table class="potential_hits">
            <?php
            /**
             * @param string $property the property to check for
             * @param array $potential_hits the potential hits to check
             * @return bool true if none of the potential hits has a value for the property, false otherwise
             */
            function is_empty($property, $potential_hits)
            {
                return array_reduce($potential_hits, function ($carry, $potential_hit) use ($property) {
                    return $carry && empty($potential_hit[$property]);
                }, true);
            }

            $potential_hits = $misuse->getPotentialHits();
            $columns = array_filter(array_keys(current($potential_hits)), function ($key) use ($columns_to_ignore, $potential_hits) {
                return !in_array($key, $columns_to_ignore) && !is_empty($key, $potential_hits);
            });
            sort($columns);
            ?>
        

        <tr>
            <th>Hit</th>
            <th>Rank</th>
            <?php foreach($columns as $column) : ?>
                <th><?= htmlspecialchars(ucwords(str_replace("_", " ", $column))); ?></th>
            <?php endforeach; ?>
            <th>Violation Types</th>
        </tr>
    
        <?php foreach($potential_hits as $hit) : ?>
        <tr>
            <td>
            <?php if($user && $is_reviewer) : ?>
                <select name="review_hit[<?= htmlspecialchars($hit['rank']); ?>][hit]" title="Decision" size="1" >
                    <?php if($review && strcmp($review->getHitDecision($hit['rank']), "No") === 0) : ?>
                        <option selected="selected" value="No" >No</option>
                    <?php else : ?>
                        <option value="No" >No</option>
                    <?php endif;?>
                    <?php if($review && strcmp($review->getHitDecision($hit['rank']), "Yes") === 0) : ?>
                    <option selected="selected" value="Yes" >Yes</option>
                    <?php else : ?>
                    <option value="Yes" >Yes</option>
                    <?php endif;?>
                    <?php if($review && strcmp($review->getHitDecision($hit['rank']), "?") === 0) : ?>
                        <option selected="selected" value="?" >?</option>
                    <?php else : ?>
                        <option value="?" >?</option>
                    <?php endif;?>
                </select>
            <?php elseif($review) : ?>
                <?php if(!$review->getHitDecision($hit['rank'])) : ?>
                    No
                <? else : ?>
                    <?= htmlspecialchars($review->getHitDecision($hit['rank'])); ?>
                <?php endif; ?>
            <?php elseif($user) : ?>
                No
            <?php else : ?>
                ?
            <?php endif;?>
            </td>
            <td>
                <?= htmlspecialchars($hit['rank']); ?>
            </td>
            <?php foreach($columns as $column) : ?>
            <td>
                <?php if(strpos($hit[$column], ";") !== false) : ?>
                    <ul>
                        <?php foreach(explode(";", $hit[$column]) as $v) : ?>
                            <li><?= htmlspecialchars($v); ?></li>
                        <?php endforeach; ?>
                    </ul>
                <?php elseif(strlen($hit[$column]) > 4 && in_array(substr($hit[$column], -4), [".png", ".svg"])) : ?>
                    <img src="<?= "{$uploads_url_prefix}/{$experiment->getId()}/{$detector->name}/{$misuse->getProject()}/{$misuse->getVersion()}/{$hit[$column]}" ?>" />
                <?php else : ?>
                    <?= htmlspecialchars($hit[$column]); ?>
                <?php endif; ?>
            </td>
            <?php endforeach; ?>
            <td>
                    <?php if($experiment->getId() === "ex2") : ?>
                        <select name="review_hit[<?= htmlspecialchars($hit['rank']); ?>][types][]" title="Violation Types" size="10" multiple <?= ($user && $is_reviewer) ? "" : "disabled" ?>>
                            <?php $add = true ?>
                            <?php if($review) : ?>
                            <?php foreach($review->getHitViolationTypes($hit['rank']) as $t) : ?>
                                <?php if($t === "missing/call") : ?>
                                    <option selected="selected" value="missing/call">missing/call</option>
                                    <?php $add = false ?>
                                <?php endif; ?>
                            <?php endforeach; ?>
                            <?php endif; ?>
                            <?php if($add) : ?>
                                <option value="missing/call">missing/call</option>
                            <?php endif; ?>
                            <?php $add = true ?>
                            <?php if($review) : ?>
                            <?php foreach($review->getHitViolationTypes($hit['rank']) as $t) : ?>
                                <?php if($t === "missing/condition/null_check") : ?>
                                    <option selected="selected" value="missing/condition/null_check">missing/condition/null_check</option>
                                    <?php $add = false ?>
                                <?php endif; ?>
                            <?php endforeach; ?>
                            <?php endif; ?>
                            <?php if($add) : ?>
                                <option value="missing/condition/null_check">missing/condition/null_check</option>
                            <?php endif; ?>
                            <?php $add = true ?>
                            <?php if($review) : ?>
                            <?php foreach($review->getHitViolationTypes($hit['rank']) as $t) : ?>
                                <?php if($t === "missing/condition/value_or_state") : ?>
                                    <option selected="selected" value="missing/condition/value_or_state">missing/condition/value_or_state</option>
                                    <?php $add = false ?>
                                <?php endif; ?>
                            <?php endforeach; ?>
                            <?php endif; ?>
                            <?php if($add) : ?>
                                <option value="missing/condition/value_or_state">missing/condition/value_or_state</option>
                            <?php endif; ?>
                            <?php $add = true ?>
                            <?php if($review) : ?>
                            <?php foreach($review->getHitViolationTypes($hit['rank']) as $t) : ?>
                                <?php if($t === "missing/condition/synchronization") : ?>
                                    <option selected="selected" value="missing/condition/synchronization">missing/condition/synchronization</option>
                                    <?php $add = false ?>
                                <?php endif; ?>
                            <?php endforeach; ?>
                            <?php endif; ?>
                            <?php if($add) : ?>
                                <option value="missing/condition/synchronization">missing/condition/synchronization</option>
                            <?php endif; ?>
                            <?php $add = true ?>
                            <?php if($review) : ?>
                            <?php foreach($review->getHitViolationTypes($hit['rank']) as $t) : ?>
                                <?php if($t === "missing/exception_handling") : ?>
                                    <option selected="selected" value="missing/exception_handling">missing/exception_handling</option>
                                    <?php $add = false ?>
                                <?php endif; ?>
                            <?php endforeach; ?>
                            <?php endif; ?>
                            <?php if($add) : ?>
                                <option value="missing/exception_handling">missing/exception_handling</option>
                            <?php endif; ?>
                            <?php $add = true ?>
                            <?php if($review) : ?>
                            <?php foreach($review->getHitViolationTypes($hit['rank']) as $t) : ?>
                                <?php if($t === "superfluous/call") : ?>
                                    <option selected="selected" value="superfluous/call">superfluous/call</option>
                                    <?php $add = false ?>
                                <?php endif; ?>
                            <?php endforeach; ?>
                            <?php endif; ?>
                            <?php if($add) : ?>
                                <option value="superfluous/call">superfluous/call</option>
                            <?php endif; ?>
                            <?php $add = true ?>
                            <?php if($review) : ?>
                            <?php foreach($review->getHitViolationTypes($hit['rank']) as $t) : ?>
                                <?php if($t === "superfluous/condition") : ?>
                                    <option selected="selected" value="superfluous/condition">superfluous/condition</option>
                                    <?php $add = false ?>
                                <?php endif; ?>
                            <?php endforeach; ?>
                            <?php endif; ?>
                            <?php if($add) : ?>
                                <option value="superfluous/condition">superfluous/condition</option>
                            <?php endif; ?>
                            <?php $add = true ?>
                            <?php if($review) : ?>
                            <?php foreach($review->getHitViolationTypes($hit['rank']) as $t) : ?>
                                <?php if($t === "superfluous/exception_handling") : ?>
                                    <option selected="selected" value="superfluous/exception_handling">superfluous/exception_handling</option>
                                    <?php $add = false ?>
                                <?php endif; ?>
                            <?php endforeach; ?>
                            <?php endif; ?>
                            <?php if($add) : ?>
                                <option value="superfluous/exception_handling">superfluous/exception_handling</option>
                            <?php endif; ?>
                            <?php $add = true ?>
                            <?php if($review) : ?>
                            <?php foreach($review->getHitViolationTypes($hit['rank']) as $t) : ?>
                                <?php if($t === "misplaced/call") : ?>
                                    <option selected="selected" value="misplaced/call">misplaced/call</option>
                                    <?php $add = false ?>
                                <?php endif; ?>
                            <?php endforeach; ?>
                            <?php endif; ?>
                            <?php if($add) : ?>
                                <option value="misplaced/call">misplaced/call</option>
                            <?php endif; ?>
                            <?php $add = true ?>
                            <?php if($review) : ?>
                            <?php foreach($review->getHitViolationTypes($hit['rank']) as $t) : ?>
                                <?php if($t === "missing/condition/context") : ?>
                                    <option selected="selected" value="missing/condition/context">missing/condition/context</option>
                                    <?php $add = false ?>
                                <?php endif; ?>
                            <?php endforeach; ?>
                            <?php endif; ?>
                            <?php if($add) : ?>
                                <option value="missing/condition/context">missing/condition/context</option>
                            <?php endif; ?>
                            <?php $add = true ?>
                            <?php if($review) : ?>
                            <?php foreach($review->getHitViolationTypes($hit['rank']) as $t) : ?>
                                <?php if($t === "misplaced/condition/null_check") : ?>
                                    <option selected="selected" value="misplaced/condition/null_check">misplaced/condition/null_check</option>
                                    <?php $add = false ?>
                                <?php endif; ?>
                            <?php endforeach; ?>
                            <?php endif; ?>
                            <?php if($add) : ?>
                                <option value="misplaced/condition/null_check">misplaced/condition/null_check</option>
                            <?php endif; ?>
                            <?php $add = true ?>
                            <?php if($review) : ?>
                            <?php foreach($review->getHitViolationTypes($hit['rank']) as $t) : ?>
                                <?php if($t === "misplaced/condition/value_or_state") : ?>
                                    <option selected="selected" value="misplaced/condition/value_or_state">misplaced/condition/value_or_state</option>
                                    <?php $add = false ?>
                                <?php endif; ?>
                            <?php endforeach; ?>
                            <?php endif; ?>
                            <?php if($add) : ?>
                                <option value="misplaced/condition/value_or_state">misplaced/condition/value_or_state</option>
                            <?php endif; ?>
                            <?php $add = true ?>
                            <?php if($review) : ?>
                            <?php foreach($review->getHitViolationTypes($hit['rank']) as $t) : ?>
                                <?php if($t === "misplaced/condition/synchronization") : ?>
                                    <option selected="selected" value="misplaced/condition/synchronization">misplaced/condition/synchronization</option>
                                    <?php $add = false ?>
                                <?php endif; ?>
                            <?php endforeach; ?>
                            <?php endif; ?>
                            <?php if($add) : ?>
                                <option value="misplaced/condition/synchronization">misplaced/condition/synchronization</option>
                            <?php endif; ?>
                            <?php $add = true ?>
                            <?php if($review) : ?>
                            <?php foreach($review->getHitViolationTypes($hit['rank']) as $t) : ?>
                                <?php if($t === "misplaced/condition/context") : ?>
                                    <option selected="selected" value="misplaced/condition/context">misplaced/condition/context</option>
                                    <?php $add = false ?>
                                <?php endif; ?>
                            <?php endforeach; ?>
                            <?php endif; ?>
                            <?php if($add) : ?>
                                <option value="misplaced/condition/context">misplaced/condition/context</option>
                            <?php endif; ?>
                            <?php $add = true ?>
                            <?php if($review) : ?>
                            <?php foreach($review->getHitViolationTypes($hit['rank']) as $t) : ?>
                                <?php if($t === "superfluous/condition/null_check") : ?>
                                    <option selected="selected" value="superfluous/condition/null_check">superfluous/condition/null_check</option>
                                    <?php $add = false ?>
                                <?php endif; ?>
                            <?php endforeach; ?>
                            <?php endif; ?>
                            <?php if($add) : ?>
                                <option value="superfluous/condition/null_check">superfluous/condition/null_check</option>
                            <?php endif; ?>
                            <?php $add = true ?>
                            <?php if($review) : ?>
                            <?php foreach($review->getHitViolationTypes($hit['rank']) as $t) : ?>
                                <?php if($t === "superfluous/condition/value_or_state") : ?>
                                    <option selected="selected" value="superfluous/condition/value_or_state">superfluous/condition/value_or_state</option>
                                    <?php $add = false ?>
                                <?php endif; ?>
                            <?php endforeach; ?>
                            <?php endif; ?>
                            <?php if($add) : ?>
                                <option value="superfluous/condition/value_or_state">superfluous/condition/value_or_state</option>
                            <?php endif; ?>
                            <?php $add = true ?>
                            <?php if($review) : ?>
                            <?php foreach($review->getHitViolationTypes($hit['rank']) as $t) : ?>
                                <?php if($t === "superfluous/condition/synchronization") : ?>
                                    <option selected="selected" value="superfluous/condition/synchronization">superfluous/condition/synchronization</option>
                                    <?php $add = false ?>
                                <?php endif; ?>
                            <?php endforeach; ?>
                            <?php endif; ?>
                            <?php if($add) : ?>
                                <option value="superfluous/condition/synchronization">superfluous/condition/synchronization</option>
                            <?php endif; ?>
                            <?php $add = true ?>
                            <?php if($review) : ?>
                            <?php foreach($review->getHitViolationTypes($hit['rank']) as $t) : ?>
                                <?php if($t === "superfluous/condition/context") : ?>
                                    <option selected="selected" value="superfluous/condition/context">superfluous/condition/context</option>
                                    <?php $add = false ?>
                                <?php endif; ?>
                            <?php endforeach; ?>
                            <?php endif; ?>
                            <?php if($add) : ?>
                                <option value="superfluous/condition/context">superfluous/condition/context</option>
                            <?php endif; ?>
                            <?php $add = true ?>
                            <?php if($review) : ?>
                            <?php foreach($review->getHitViolationTypes($hit['rank']) as $t) : ?>
                                <?php if($t === "misplaced/exception_handling") : ?>
                                    <option selected="selected" value="misplaced/exception_handling">misplaced/exception_handling</option>
                                    <?php $add = false ?>
                                <?php endif; ?>
                            <?php endforeach; ?>
                            <?php endif; ?>
                            <?php if($add) : ?>
                                <option value="misplaced/exception_handling">misplaced/exception_handling</option>
                            <?php endif; ?>
                            <?php $add = true ?>
                            <?php if($review) : ?>
                            <?php foreach($review->getHitViolationTypes($hit['rank']) as $t) : ?>
                                <?php if($t === "missing/iteration") : ?>
                                    <option selected="selected" value="missing/iteration">missing/iteration</option>
                                    <?php $add = false ?>
                                <?php endif; ?>
                            <?php endforeach; ?>
                            <?php endif; ?>
                            <?php if($add) : ?>
                                <option value="missing/iteration">missing/iteration</option>
                            <?php endif; ?>
                            <?php $add = true ?>
                            <?php if($review) : ?>
                            <?php foreach($review->getHitViolationTypes($hit['rank']) as $t) : ?>
                                <?php if($t === "misplaced/iteration") : ?>
                                    <option selected="selected" value="misplaced/iteration">misplaced/iteration</option>
                                    <?php $add = false ?>
                                <?php endif; ?>
                            <?php endforeach; ?>
                            <?php endif; ?>
                            <?php if($add) : ?>
                                <option value="misplaced/iteration">misplaced/iteration</option>
                            <?php endif; ?>
                            <?php $add = true ?>
                            <?php if($review) : ?>
                            <?php foreach($review->getHitViolationTypes($hit['rank']) as $t) : ?>
                                <?php if($t === "superfluous/iteration") : ?>
                                    <option selected="selected" value="superfluous/iteration">superfluous/iteration</option>
                                    <?php $add = false ?>
                                <?php endif; ?>
                            <?php endforeach; ?>
                            <?php endif; ?>
                            <?php if($add) : ?>
                                <option value="superfluous/iteration">superfluous/iteration</option>
                            <?php endif; ?>
                        </select>
                    <?php else : ?>
                        <?php if($misuse->hasViolationTypes()) : ?>
                            <?php if($user && $is_reviewer) : ?>
                                <select name="review_hit[<?= htmlspecialchars($hit['rank']); ?>][types][]" title="Violation Types" size="<?= htmlspecialchars(count($misuse->getViolationTypes())); ?>" multiple>
                            <?php else : ?>
                                <select disabled name="review_hit[<?= htmlspecialchars($hit['rank']); ?>][types][]" title="Violation Types" size="<?= htmlspecialchars(count($misuse->getViolationTypes())); ?>" multiple>
                            <?php endif; ?>
                                <?php foreach($misuse->getViolationTypes() as $v) : ?>
                                    <?php $add = true ?>
                                    <?php if($review && $review->hasHitViolationTypes($hit['rank'])) : ?>
                                        <?php foreach($review->getHitViolationTypes($hit['rank']) as $t) : ?>
                                            <?php if($t === $v) : ?>
                                                <option selected="selected" value="<?= htmlspecialchars($v); ?>"><?= htmlspecialchars($v); ?></option>
                                                <?php $add = false ?>
                                            <?php endif; ?>
                                        <?php endforeach; ?>
                                    <?php endif; ?>
                                    <?php if($add) : ?>
                                        <option value="<?= htmlspecialchars($v); ?>"><?= htmlspecialchars($v); ?></option>
                                    <?php endif; ?>
                                <?php endforeach; ?>
                            </select>
                        <?php endif;?>

                    <?php endif; ?>
            </td>
        </tr>
       <?php endforeach; ?>
       </table>
        <?php endif; ?>
            <?php if($user && $is_reviewer) :?>
                <table class="invisible">
                <tr><td>Reviewer Name:</td>
                    <td><?= htmlspecialchars($user); ?></td></tr>
                <tr><td class="vtop"><label for="review_comment">Comment</label>:</td>
                    <td>
                    <?php if($review) : ?>
                        <textarea id="review_comment" name="review_comment" cols="80" rows="5"><?= htmlspecialchars($review->getComment()); ?></textarea>
                    <?php else : ?>
                        <textarea id="review_comment" name="review_comment" cols="80" rows="5"></textarea>
                    <?php endif; ?>
                    </td></tr>
                </table>
                <input type="hidden" name="review_name" value="<?= htmlspecialchars($user); ?>"/>
                <input type="hidden" name="review_exp" value="<?= htmlspecialchars($experiment->getId()); ?>">
                <input type="hidden" name="review_detector" value="<?= htmlspecialchars($detector->name); ?>">
                <input type="hidden" name="review_project" value="<?= htmlspecialchars($misuse->getProject()); ?>">
                <input type="hidden" name="review_version" value="<?= htmlspecialchars($misuse->getVersion()); ?>">
                <input type="hidden" name="review_misuse" value="<?= htmlspecialchars($misuse->id); ?>">
                <input type="hidden" name="origin" value="<?= htmlspecialchars($origin_path); ?>">
                <input type="submit" value="Save Review" />
                </form>
        <?php endif; ?>
        <?php if($review && !$user && !$is_reviewer) :?>
                <table class="invisible">
                    <tr><td>Reviewer Name:</td>
                        <td><?= htmlspecialchars($review->getReviewerName()); ?></td></tr>
                    <tr><td class="vtop"><label for="review_comment">Comment</label>:</td>
                        <td>
                                <textarea disabled id="review_comment" name="review_comment" cols="80" rows="5"><?= htmlspecialchars($review->getComment()); ?></textarea>
                        </td></tr>
                </table>
        <?php endif; ?>


            <script>
                function show(b){
                    var elem = document.getElementById("snippet_form");
                    if(elem.style.display === "none"){
                        elem.style.display = "block";
                    }
                    b.type = "hidden";
                }
            </script>
            </body>
        </html>
    
