<?php
/**
 * @var string $user the logged in user, if any
 *
 * @var string $site_base_url
 * @var string $public_url_prefix
 * @var string $private_url_prefix
 * @var string $url_prefix the public or private url prefix, depending on whether the user is logged in
 *
 * @var string $path the current route path
 * @var string $origin_param url parameter that carries the $path
 * @var string $origin_path referrer path
 *
 * @var array $experiments all experiments (Experiment)
 * @var array $detectors detectors (Detector) with results per experiment
 * @var array $results
 * @var int $ex2_review_size max number of reviews (per project) to include in statistics
 */
use MuBench\ReviewSite\Model\RunsResult;
?>
<html>
<head>
    <link rel="stylesheet" type="text/css" href="<?= $site_base_url ?>style/style.css"/>
</head>
<body>
<?php include "includes/menu.phtml" ?>

<h1>Statistics</h1>

<h2>Experiment 1</h2>

<table>
    <thead>
    <tr>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th colspan="3">Agreements</th>
        <th colspan="3">Disagreements</th>
        <th colspan="3">Kappa</th>
        <th></th>
        <th></th>
    </tr>
    <tr>
        <th>Detector</th>
        <th>Projects</th>
        <th>Synthetics</th>
        <th>Misuses</th>
        <th>Potential Hits</th>
        <th>Open Reviews</th>
        <th>Open '?'</th>
        <th>Yes</th>
        <th>No</th>
        <th>Total</th>
        <th>Yes/No</th>
        <th>No/Yes</th>
        <th>Total</th>
        <th>p<sub>0</sub></th>
        <th>p<sub>e</sub></th>
        <th>Score</th>
        <th>Hits</th>
        <th>Recall</th>
    </tr>
    </thead>

    <?php foreach ($results["ex1"] as $result) : /** @var $result RunsResult */ ?>
        <tbody>
        <tr>
            <td><?= $result->getDisplayName() ?></td>
            <td class="right"><?= $result->number_of_projects ?></td>
            <td class="right"><?= $result->number_of_synthetics ?></td>
            <td class="right"><?= $result->number_of_misuses ?></td>
            <td class="right"><?= $result->misuses_to_review ?></td>
            <td class="right"><?= $result->open_reviews ?></td>
            <td class="right"><?= $result->number_of_needs_clarification ?></td>

            <td class="right"><?= $result->yes_agreements ?></td>
            <td class="right"><?= $result->no_agreements ?></td>
            <td class="right"><?= $result->getNumberOfAgreements() ?></td>
            <td class="right"><?= $result->yes_no_disagreements ?></td>
            <td class="right"><?= $result->no_yes_disagreements ?></td>
            <td class="right"><?= $result->getNumberOfDisagreements() ?></td>

            <td class="right"><?= round($result->getKappaP0(), 3) ?></td>
            <td class="right"><?= round($result->getKappaPe(), 3) ?></td>
            <td class="right"><?= round($result->getKappaScore(), 3) ?></td>
            <td class="right"><?= $result->number_of_hits ?></td>
            <td class="right"><?= round($result->getRecall() * 100, 1) ?>%</td>
        </tr>
        </tbody>
    <?php endforeach; ?>
</table>

<h2>Experiment 2</h2>

<form action="" method="get">
    <label for="ex2_review_size">Max. Reviews per Project</label>:
    <input type="text" id="ex2_review_size" name="ex2_review_size" value="<?= $ex2_review_size ?>" />
    <input type="submit" value="update" />
</form>

<table>
    <thead>
    <tr>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th colspan="3">Agreements</th>
        <th colspan="3">Disagreements</th>
        <th colspan="3">Kappa</th>
        <th></th>
        <th></th>
    </tr>
    <tr>
        <th>Detector</th>
        <th>Projects</th>
        <th>Potential Hits</th>
        <th>Open Reviews</th>
        <th>Open '?'</th>
        <th>Yes</th>
        <th>No</th>
        <th>Total</th>
        <th>Yes/No</th>
        <th>No/Yes</th>
        <th>Total</th>
        <th>p<sub>0</sub></th>
        <th>p<sub>e</sub></th>
        <th>Score</th>
        <th>Hits</th>
        <th>Precision</th>
    </tr>
    </thead>

    <?php foreach ($results["ex2"] as $result) : /** @var $result RunsResult */ ?>
        <tbody>
        <tr>
            <td><?= $result->getDisplayName() ?></td>
            <td class="right"><?= $result->number_of_projects ?></td>
            <td class="right"><?= $result->misuses_to_review ?></td>
            <td class="right"><?= $result->open_reviews ?></td>
            <td class="right"><?= $result->number_of_needs_clarification ?></td>

            <td class="right"><?= $result->yes_agreements ?></td>
            <td class="right"><?= $result->no_agreements ?></td>
            <td class="right"><?= $result->getNumberOfAgreements() ?></td>
            <td class="right"><?= $result->yes_no_disagreements ?></td>
            <td class="right"><?= $result->no_yes_disagreements ?></td>
            <td class="right"><?= $result->getNumberOfDisagreements() ?></td>

            <td class="right"><?= round($result->getKappaP0(), 3) ?></td>
            <td class="right"><?= round($result->getKappaPe(), 3) ?></td>
            <td class="right"><?= round($result->getKappaScore(), 3) ?></td>
            <td class="right"><?= $result->number_of_hits ?></td>
            <td class="right"><?= round($result->getPrecision() * 100, 1) ?>%</td>
        </tr>
        </tbody>
    <?php endforeach; ?>
</table>

<h2>Experiment 3</h2>

<table>
    <thead>
    <tr>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th colspan="3">Agreements</th>
        <th colspan="3">Disagreements</th>
        <th colspan="3">Kappa</th>
        <th></th>
        <th></th>
    </tr>
    <tr>
        <th>Detector</th>
        <th>Projects</th>
        <th>Misuses</th>
        <th>Potential Hits</th>
        <th>Open Reviews</th>
        <th>Open '?'</th>
        <th>Yes</th>
        <th>No</th>
        <th>Total</th>
        <th>Yes/No</th>
        <th>No/Yes</th>
        <th>Total</th>
        <th>p<sub>0</sub></th>
        <th>p<sub>e</sub></th>
        <th>Score</th>
        <th>Hits</th>
        <th>Recall</th>
    </tr>
    </thead>

    <?php foreach ($results["ex3"] as $key => $result) : /** @var RunsResult $results */ ?>
        <tbody>
        <tr>
            <td><?= $result->getDisplayName() ?></td>
            <td class="right"><?= $result->number_of_projects ?></td>
            <td class="right"><?= $result->number_of_misuses ?></td>
            <td class="right"><?= $result->misuses_to_review ?></td>
            <td class="right"><?= $result->open_reviews ?></td>
            <td class="right"><?= $result->number_of_needs_clarification ?></td>

            <td class="right"><?= $result->yes_agreements ?></td>
            <td class="right"><?= $result->no_agreements ?></td>
            <td class="right"><?= $result->getNumberOfAgreements() ?></td>
            <td class="right"><?= $result->yes_no_disagreements ?></td>
            <td class="right"><?= $result->no_yes_disagreements ?></td>
            <td class="right"><?= $result->getNumberOfDisagreements() ?></td>

            <td class="right"><?= round($result->getKappaP0(), 3) ?></td>
            <td class="right"><?= round($result->getKappaPe(), 3) ?></td>
            <td class="right"><?= round($result->getKappaScore(), 3) ?></td>
            <td class="right"><?= $result->number_of_hits ?></td>
            <td class="right"><?= round($result->getRecall() * 100, 1) ?>%</td>
        </tr>
        </tbody>
    <?php endforeach; ?>
</table>

</body>
</html>
