<?php
/**
 * @var string $user the logged in user, if any
 *
 * @var string $site_base_url
 * @var string $public_url_prefix
 * @var string $private_url_prefix
 * @var string $url_prefix the public or private url prefix, depending on whether the user is logged in
 *
 * @var string $path the current route path
 * @var string $origin_param url parameter that carries the $path
 * @var string $origin_path referrer path
 *
 * @var array $experiments all experiments (Experiment)
 * @var array $detectors detectors (Detector) with results per experiment
 *
 * @var Parsedown $markdown_parser markdown parser
 *
 * @var array $misuses
 * @var callable $detectorName function to resolve router paths
 */

use MuBench\ReviewSite\Models\ReviewState;

?>
<html>
<head>
    <title>MuBench :: Open Reviews</title>
    <link rel="stylesheet" type="text/css" href="<?= $site_base_url ?>css/style.css" />
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
<?php include "includes/menu.phtml"; ?>

<h1>Experiment: <?= htmlspecialchars($experiment->id); ?></h1>
<table>
    <thead>
    <tr>
        <th>Detector</th>
        <th>Project</th>
        <th>Version</th>
        <th>Misuse</th>
        <th>Decision</th>
        <th>Reviews</th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    <?php $last_project = ""; $version = ""; ?>
    <?php foreach($open_misuses as $detector => $misuses) : ?>
    <?php foreach($misuses as $misuse) : /** @var \MuBench\ReviewSite\Models\Misuse $misuse */ ?>
        <?php
        $project = $misuse->getProject();
        $new_project = strcmp($last_project, $misuse->getProject()) !== 0;
        $last_project = $project;
        $new_version = strcmp($version, $misuse->getVersion()) !== 0;
        $version = $misuse->getVersion();
        ?>
        <?php
        $classes = [];
        if($new_project) $classes[] = "top";
        $style_classes = implode(" ", $classes);
        ?>
        <tr>
            <td class="<?= $style_classes ?>">
                <?= $new_project ? $markdown_parser->text($detectorName($detector)) : ""; ?></td>
            <td class="<?= $style_classes ?>">
                <?= $new_project ? $markdown_parser->text($project) : ""; ?></td>
            <td class="<?= $style_classes ?>">
                <?= $new_version ? $markdown_parser->text($version) : ""; ?></td>
            <td class="<?= $style_classes ?>">
                <?= $markdown_parser->text($misuse->misuse_muid); ?></td>
            <?php
            $resolution_review = $pathFor('review', array('experiment_id' => $experiment->id, 'detector_muid' => $detectorName($misuse->detector->muid), 'project_muid' => $misuse->getProject(), 'version_muid' => $misuse->getVersion(), 'misuse_muid' => $misuse->misuse_muid, 'reviewer_name' => ($blind_mode ? $resolution_reviewer->id : $resolution_reviewer->name)));
            ?>
            <td class="<?= $style_classes ?>">
                <?php $review_state = $misuse->getReviewState() ?>
                <?php if ($review_state == ReviewState::NOTHING_TO_REVIEW): ?>
                <?php elseif ($review_state == ReviewState::NEEDS_REVIEW): ?>
                    <i class="fa fa-search" aria-hidden="true" style="color:red;" title="Needs Review"></i>
                <?php elseif ($review_state == ReviewState::NEEDS_CLARIFICATION): ?>
                    <i class="fa fa-question-circle" aria-hidden="true" style="color:blue;" title="Needs Clarification"></i>
                <?php elseif ($review_state == ReviewState::DISAGREEMENT): ?>
                    <a href="<?= $resolution_review ?>"><i class="fa fa-exclamation-triangle" aria-hidden="true" style="color:red;" title="Disagreement"></i></a>
                <?php elseif ($review_state == ReviewState::AGREEMENT_YES): ?>
                    <i class="fa fa-thumbs-o-up" aria-hidden="true" style="color:green;" title="Agreement: Yes"></i>
                <?php elseif ($review_state == ReviewState::AGREEMENT_NO): ?>
                    <i class="fa fa-thumbs-o-down" aria-hidden="true" style="color:darkred;" title="Agreement: No"></i>
                <?php elseif ($review_state == ReviewState::RESOLVED_YES): ?>
                    <i class="fa fa-thumbs-o-up" aria-hidden="true" style="color:green;" title="Resolved: Yes"></i>
                    (<a href="<?= $resolution_review ?><?= $origin_param ?>"><i class="fa fa-handshake-o" aria-hidden="true" title="Resolution"></i></a>)
                <?php elseif ($review_state == ReviewState::RESOLVED_NO): ?>
                    <i class="fa fa-thumbs-o-down" aria-hidden="true" style="color:darkred;" title="Resolved: No"></i>
                    (<a href="<?= $resolution_review ?><?= $origin_param ?>"><i class="fa fa-handshake-o" aria-hidden="true" title="Resolution"></i></a>)
                <?php endif; ?>
            </td>
            <td class="<?= $style_classes ?>">
                <ul class="inline">
                    <?php foreach($misuse->getReviews() as $review) : /** @var \MuBench\ReviewSite\Models\Review $review */ ?>
                    <?php $reviewer_name = htmlspecialchars(($blind_mode ? $review->reviewer->id : $review->reviewer->name)) ?>
                        <li style="display:inline"><a href="<?= $pathFor('review', array('experiment_id' => $experiment->id, 'detector_muid' => $detectorName($misuse->detector->muid), 'project_muid' => $misuse->getProject(), 'version_muid' => $misuse->getVersion(), 'misuse_muid' => $misuse->misuse_muid, 'reviewer_name' => ($blind_mode ? $review->reviewer->id : $review->reviewer->name))) ?><?= ($blind_mode ? $review->reviewer->id : $review->reviewer->name) ?>"></a></li>
                    <?php endforeach; ?>
                </ul>
            </td>
            <td><a href="<?= $pathFor('review', array('experiment_id' => $experiment->id, 'detector_muid' => $detectorName($misuse->detector->muid), 'project_muid' => $misuse->getProject(), 'version_muid' => $misuse->getVersion(), 'misuse_muid' => $misuse->misuse_muid, 'reviewer_name' => ($blind_mode ? $user->id : $user->name)));
                            ?><?= $origin_param ?>" class="button">review</a></td>
        </tr>
        <?php
        $new_version = false;
        $new_project = false;
        ?>
    <?php endforeach; ?>
    <?php endforeach; ?>
    </tbody>
</table>
</body>
</html>
