ALTER TABLE `detectors` ENGINE=MyISAM DEFAULT CHARSET=latin1, MODIFY COLUMN `id` INTEGER AUTO_INCREMENT;

ALTER TABLE `stats` ENGINE=MyISAM DEFAULT CHARSET=latin1;

ALTER TABLE `metadata` ENGINE=MyISAM DEFAULT CHARSET=latin1;

ALTER TABLE `patterns` ENGINE=MyISAM DEFAULT CHARSET=latin1;

ALTER TABLE `reviews` ENGINE=MyISAM DEFAULT CHARSET=latin1, MODIFY COLUMN `id` INTEGER AUTO_INCREMENT;

ALTER TABLE `meta_snippets` ENGINE=MyISAM DEFAULT CHARSET=latin1;

ALTER TABLE `review_findings` ENGINE=MyISAM DEFAULT CHARSET=latin1, MODIFY COLUMN `id` INTEGER AUTO_INCREMENT;

ALTER TABLE `review_findings_type` ENGINE=MyISAM DEFAULT CHARSET=latin1;

ALTER TABLE `finding_snippets` ENGINE=MyISAM DEFAULT CHARSET=latin1;

ALTER TABLE `types` ENGINE=MyISAM DEFAULT CHARSET=latin1, MODIFY COLUMN `name` varchar(100) UNIQUE;