#!/bin/bash

image=$1
tag=$2
version="$(./deploy_version $tag)"
repo=$image:$tag

echo "Building $repo $version..."
docker build -f docker/Dockerfile -t $repo --build-arg mubench_version=$version .

echo "Deploying $repo $version..."
docker push $repo
