#!/bin/bash

SCRIPT_DIR=$(dirname "$([[ "$0" = /* ]] && echo "$0" || echo "$PWD/${0#./}")")
MUBENCH_ROOT=$SCRIPT_DIR
TASKS=${MUBENCH_ROOT}/mubench.bin

source ${TASKS}/environment

if [ "$1" = "-h" ]; then
  echo "$(cat "${MUBENCH_DOCS}/mubench.txt")"
  exit 0
else
  TASK=${TASKS}/$1
  if [ -f "${TASK}" ]; then
    shift  # remove requested task argument
    source "${TASK}" "$@"
  else
    source "${TASKS}/pipeline" "$@"
  fi;
fi;
