@ECHO OFF

SET SCRIPT_DIR=%~dp0
SET MUBENCH_ROOT=%SCRIPT_DIR%
SET TASKS=%MUBENCH_ROOT%mubench.bin\

CALL %TASKS%environment.bat

SET TASK=%TASKS%%~1.bat
IF EXIST %TASK% (
  SHIFT
  CALL %TASK% %*
) ELSE (
  CALL %TASKS%pipeline.bat %*
)