#!/bin/bash

SCRIPT_DIR=$(dirname "$([[ "$0" = /* ]] && echo "$0" || echo "$PWD/${0#./}")")
MUBENCH_ROOT=$SCRIPT_DIR
TASKS=${MUBENCH_ROOT}/mubench.bin

source "${TASKS}/environment"

HELP=f
if [[ "$*" =~ "-h" ]]; then
  HELP=t
fi

if [ $HELP ] && [ $# = 1 ]; then
  docker run --rm -v "$MUBENCH_ROOT":/mubench ${MUBENCH_PIPELINE_DOCKER_IMAGE} python3 ${MUBENCH_DOCS}/mubench.py "$@"
  exit 0
else
  TASK="${TASKS}/$1"
  DOC="${MUBENCH_DOCS}/$1.py"
  if [ -f "${TASK}" ]; then
    shift  # remove requested task argument
    if [ $HELP ] && [ -f "${MUBENCH_ROOT}/${DOC}" ]; then
      docker run --rm -v "$MUBENCH_ROOT":/mubench ${MUBENCH_PIPELINE_DOCKER_IMAGE} python3 ${DOC} "$@"
      exit 0
    fi;
    source "${TASK}" "$@"
  else
    source "${TASKS}/pipeline" "$@"
  fi;
fi;
