@ECHO OFF

SETLOCAL SCRIPT_DIR=%~dp0
SETLOCAL "SCRIPT_DIR=%SCRIPT_DIR:\=/%"
SET MUBENCH_ROOT=%SCRIPT_DIR%
SET TASKS=%MUBENCH_ROOT%\mubench.bin

%TASKS%\environment.bat

SETLOCAL TASK="%MUBENCH_ROOT%\%~1.bin"
IF EXIST %TASK% (
  SHIFT
  CALL %TASK% %*
) ELSE (
  CALL "%MUBENCH_ROOT%\pipeline.bin" %*
)
