#!/bin/bash

SCRIPT_DIR=$(dirname "$([[ "$0" = /* ]] && echo "$0" || echo "$PWD/${0#./}")")
MUBENCH_ROOT=$SCRIPT_DIR

MUBENCH_REVIEWSITE_DATA_VOLUME=mubench-reviews

MUBENCH_DOCS=mubench.docs


docker run -it --rm  -p 8080:80 -v mubench-checkouts:/mubench/checkouts -v mubench-findings:/mubench/findings -v mubench-reviews:/mubench/reviewsite-data -v "${MUBENCH_ROOT}/mubench.reviewsite":/mubench-reviewsite svamann/mubench:latest
