#!/bin/bash

if [ "$1" = 'start' ]; then
  echo "Starting MUBench review site on localhost..."
  php -S 0.0.0.0:80 -t ./mubench.reviewsite > /dev/null 2>&1 &
elif [ "$1" = 'stop' ]; then
  echo "Stopping MUBench review site..."
  killall -9 php
else
  echo "Unknown task:" $1
  echo "Chose one of {start,stop}"
fi;
