#!/bin/bash 

export MUBENCH_DOCKER_IMAGE_USERNAME=svamann 
export MUBENCH_DOCKER_IMAGE_TAG=latest 
export MUBENCH_PIPELINE_CHECKOUTS_VOLUME=mubench-checkouts 
export MUBENCH_PIPELINE_FINDINGS_VOLUME=mubench-findings 
export MUBENCH_REVIEWSITE_DOCKER_CID=mubench-reviewsite-standalone 
export MUBENCH_REVIEWSITE_PORT=8080 
export MUBENCH_REVIEWSITE_DATA_VOLUME=mubench-reviews 
