key_findings_file = "target"
key_run_file = "run_info"
key_detector_mode = "detector_mode"
key_training_src_path = "training_src_path"
key_training_classes_path = "training_classpath"
key_target_src_paths = "target_src_path"
key_target_classes_paths = "target_classpath"
key_dependency_classpath = "dep_classpath"
