<?php
/**
 * @var \MuBench\ReviewSite\Extensions\MenuViewExtension $menuViewExtension
 * @var Experiment $experiment the selected experiment
 * @var Detector $detector the selected detector
 */

use MuBench\ReviewSite\Models\Detector;
use MuBench\ReviewSite\Models\Experiment;
use MuBench\ReviewSite\Models\ReviewState;

$review_states = $menuViewExtension->getReviewStates($experiment, $detector, $ex2_review_size, $user);
?>

<?php if ($review_states[ReviewState::NEEDS_REVIEW]["global"]): ?>
    <i class="fa fa-search" aria-hidden="true" style="color:<?= $review_states[ReviewState::NEEDS_REVIEW]['personal'] ? "red" : "grey" ?>;" title="Needs Review"></i>
<?php endif;?>
<?php if ($review_states[ReviewState::NEEDS_CLARIFICATION]): ?>
    <i class="fa fa-question-circle" aria-hidden="true" style="color:blue;" title="Needs Clarification"></i>
<?php endif;?>
<?php if ($review_states[ReviewState::DISAGREEMENT]): ?>
    <i class="fa fa-exclamation-triangle" aria-hidden="true" style="color:red;" title="Disagreement"></i>
<?php endif;?>
