<?php
/**
 * @var boolean $logged whether the user is logged in or not
 * @var string $base_url the site's public base url
 * @var string $private_url the site's private base url
 * @var string $route_url the current route path
 *
 * @var string $experiment the id of the experiment currently displayed, if any
 * @var string $detector the id of the detector currently displayed, if any
 */
?>
<div id="header">
    <div id="title">
        <a href="https://github.com/stg-tud/MUBench" title="MUBench Project">
            <img id="logo" src="<?= $root_url ?>/assets/images/mubench_logo.png" />
        </a>
        <a href="<?= $root_url ?>" title="Home">
            Review<br/>Site
        </a>
    </div>

    <ol id="menu">
        <?php if(!$logged) : ?>
            <li><a href="<?= $private_url; ?><?= $route_url; ?>">Login</a></li>
        <?php endif; ?>

        <?php if($logged) : ?>
            <li><a href="<?= $private_url; ?>overview">My Reviews</a></li>
            <li><a href="<?= $private_url; ?>todo">Open Reviews</a></li>
        <?php endif; ?>

        <li><a href="<?= $base_url; ?>stats">Statistics</a></li>
    </ol>

    <ol id="breadcrumbs">
        <?php
        $url_prefix = $logged ? $private_url : $base_url;
        ?>
        <li><a href="<?= $url_prefix ?>">Home</a></li>
        <?php if($experiment) : ?>
            <li><a href="<?= $url_prefix . $experiment ?>"><?= $experiment ?></a></li>

            <?php if($detector) : ?>
                <li><a href="<?= $url_prefix .$experiment . "/" . $detector ?>"><?= $detector ?></a></li>
            <?php endif; ?>
        <?php endif; ?>
    </ol>
</div>
