<?php
/**
 * @var \MuBench\ReviewSite\Models\Reviewer $reviewer the logged in user, if any
 * @var callable $pathFor function to resolve router paths
 * @var callable $isCurrentPath function to check if a path is the current path
 * @var callable $srcUrlFor function to resolve resources
 *
 * @var string $path the current route path
 * @var string $origin_param url parameter that carries the $path
 * @var string $origin_path referrer path
 *
 * @var array $experiments all experiments (Experiment)
 * @var array $detectors detectors (Detector) with results per experiment
 * @var Experiment $experiment the selected experiment, if any
 * @var Detector $detector the selected detector, if any
 * @var Reviewer $user the logged in user
 */

use MuBench\ReviewSite\Models\Detector;
use MuBench\ReviewSite\Models\Experiment;

?>
<div id="header">
    <div id="title">
        <a href="https://github.com/stg-tud/MUBench" title="MUBench Project">
            <img id="logo" src="<?= $srcUrlFor('assets/images/mubench_logo.png') ?>" />
        </a>
        <a href="<?= $pathFor('/') ?>" title="Home">Review<br/>Site</a>
    </div>

    <nav role="navigation">
        <ol>
            <?php $this_exp = isset($experiment) ? $experiment : null ?>
            <?php foreach ($experiments as $experiment): ?>
                <?php include "menu-experiment.phtml" ?>
            <?php endforeach ?>
            <?php $experiment = $this_exp ?>
            <li class="<?= strpos($path, '/stats') !== false ? "active" : "" ?>">
                <span>Statistics</span>
                <ul>
                    <li class="<?= $isCurrentPath('stats.tags') ? "active" : "" ?>">
                        <a href="<?= $pathFor('stats.tags') ?>">Tags</a>
                    </li>
                    <li class="<?= $isCurrentPath('stats.types') ? "active" : "" ?>">
                        <a href="<?= $pathFor('stats.types') ?>">Types</a>
                    </li>
                    <li class="<?= $isCurrentPath('stats.results') ? "active" : "" ?>">
                        <a href="<?= $pathFor('stats.results') ?>">Results</a>
                    </li>
                </ul>
            </li>
            <?php if($user) : ?>
                    <li class="right <?= strpos($path, '/stats') !== false ? "active" : "" ?>">
                    <span>Reviewer: <?= htmlspecialchars($user->name) ?></span>
                    <ul>
                <?php if($experiment) : ?>
                    <li class="right <?= $isCurrentPath('overview', array('experiment_id' => $experiment->id, 'reviewer_name' => $user->name)) ? "active" : "" ?>">
                            <a href="<?= $pathFor('overview', array('experiment_id' => $experiment->id, 'reviewer_name' => $user->name)) ?>">My Reviews</a></li>
                        <li class="right <?= $isCurrentPath('todo',  array('experiment_id' => $experiment->id, 'reviewer_name' => $user->name)) ? "active" : "" ?>">
                            <a href="<?= $pathFor('todo', array('experiment_id' => $experiment->id, 'reviewer_name' => $user->name)) ?>">Open Reviews</a></li>
                <?php endif; ?>
                        <li class="right <?= $isCurrentPath('manage.runs') ? "active" : "" ?>">
                            <a href="<?= $pathFor('manage.runs') ?>">Manage runs</a></li>
                    </ul>
                    </li>
            <?php else: ?>
                <li class="right"><a href="<?= $loginPath ?>">Login</a></li>
            <?php endif; ?>
        </ol>
    </nav>
</div>
