<?php
/**
 * @var string $user the logged in user, if any
 *
 * @var string $site_base_url
 * @var string $public_url_prefix
 * @var string $private_url_prefix
 * @var string $url_prefix the public or private url prefix, depending on whether the user is logged in
 *
 * @var string $path the current route path
 * @var string $origin_param url parameter that carries the $path
 * @var string $origin_path referrer path
 *
 * @var array $experiments all experiments (Experiment)
 * @var array $detectors detectors (Detector) with results per experiment
 * @var Experiment $experiment the selected experiment, if any
 * @var Detector $detector the selected detector, if any
 */
use MuBench\ReviewSite\Model\Detector;
use MuBench\ReviewSite\Model\Experiment;

?>
<div id="header">
    <div id="title">
        <a href="https://github.com/stg-tud/MUBench" title="MUBench Project">
            <img id="logo" src="<?= $site_base_url ?>/assets/images/mubench_logo.png" />
        </a>
        <a href="<?= $url_prefix ?>" title="Home">Review<br/>Site</a>
    </div>

    <nav role="navigation">
        <ol>
            <?php $this_exp = $experiment ?>
            <?php foreach ($experiments as $experiment): ?>
                <?php include "menu-experiment.phtml" ?>
            <?php endforeach ?>
            <?php $experiment = $this_exp ?>
            <li class="<?= strpos($path, "/stats") !== false ? "active" : "" ?>">
                <a href="<?= $public_url_prefix ?>stats">Statistics</a></li>

            <?php if($user) : ?>
                <li class="right <?= strpos($path, "/overview") !== false ? "active" : "" ?>">
                    <a href="<?= $private_url_prefix ?>overview">My Reviews</a></li>
                <li class="right <?= strpos($path, "/todo") !== false ? "active" : "" ?>">
                    <a href="<?= $private_url_prefix ?>todo">Open Reviews</a></li>
            <?php else: ?>
                <li class="right"><a href="<?= $private_url_prefix . $path ?>">Login</a></li>
            <?php endif; ?>
        </ol>
    </nav>
</div>
