<?php
/**
* @var string $project
* @var string $version
* @var array $run all run information
* @var array $additional_stats all stat columns from the run information besides project, version, runtime, result and number_of_findings
*/
?>

<i value="<?= htmlspecialchars($project) ?>_<?= htmlspecialchars($version) ?>" onclick="showModal(this)" class="fa fa-info-circle" aria-hidden="true"></i>
<div id="<?= htmlspecialchars($project) ?>_<?= htmlspecialchars($version) ?>" class="modal">
    <div class="modal-content">
                            <span class="close"
                                  id="<?= htmlspecialchars($project) ?>_<?= htmlspecialchars($version) ?>">&times;</span>
        <table class="invisible">
            <tr>
                <td><h2>Run Details</h2></td>
                <td></td>
            </tr>
            <tr>
                <td><b>Project:</b></td>
                <td><?= htmlspecialchars($project); ?></td>
            </tr>
            <tr>
                <td><b>Version:</b></td>
                <td><?= htmlspecialchars($version); ?></td>
            </tr>
            <tr>
                <td><b>Result:</b></td>
                <td><?= htmlspecialchars($run['result']); ?></td>
            </tr>
            <tr>
                <td><b># of Findings:</b></td>
                <td><?= htmlspecialchars($run['number_of_findings']); ?></td>
            </tr>
            <tr>
                <td><b>Runtime:</b></td>
                <td><?= htmlspecialchars(substr($run['runtime'], 0, 4)) . "s"; ?></td>
            </tr>
            <?php foreach ($additional_stats as $stat) : ?>
                <?php if(empty($additional_stats[$stat])): ?>
                    <tr>
                        <td><b><?= htmlspecialchars($stat) ?>:</b></td>
                        <td><?= htmlspecialchars($run[$stat]); ?></td>
                    </tr>
                <?php endif; ?>
            <?php endforeach; ?>
        </table>
    </div>
</div>
