FROM alpine:3.6

LABEL maintainer="amann@st.informatik.tu-darmstadt.de"

# Install ca-certificates so that HTTPS works consistently
RUN apk update \
 && apk add ca-certificates wget \
 && update-ca-certificates

ENV LANG=C.UTF-8

# Setup reviewsite environment
RUN apk update \
 \
 # Install PHP
 && apk add \
      php7 \
      php7-ctype \
      php7-dom \
      php7-json \
      php7-mbstring \
      php7-openssl \
      php7-pdo \
      php7-pdo_sqlite \
      php7-phar \
      php7-session \
      php7-sqlite3 \
      php7-tokenizer \
      php7-xml \
      php7-xmlwriter \
      php7-zlib \
 \
 # Install Composer
 && wget -q https://getcomposer.org/installer -O composer-setup.php \
 && php composer-setup.php --install-dir=/usr/local/bin --filename=composer \
 && rm composer-setup.php

# On run: Fire up review site on port 80
WORKDIR /mubench-reviewsite
EXPOSE 80
CMD php -S 0.0.0.0:80 -t .
STOPSIGNAL SIGTERM

# Setup review site
COPY mubench.reviewsite .
RUN composer install --no-interaction --no-dev \
 && mkdir -p /mubench-reviewsite/upload \
 && mkdir /mubench-reviewsite-data \
 && mkdir /mubench-reviewsite-data/logs \
 && touch /mubench-reviewsite-data/standalone.sqlite \
 && mv settings.docker.php settings.php
