FROM ubuntu:latest

LABEL maintainer="amann@st.informatik.tu-darmstadt.de"

# settings
ENV DEBIAN_FRONTEND noninteractive
ENV LANG=C.UTF-8 \
    GRADLE_VERSION=4.0.2 \
    GRADLE_HOME=/usr/local/gradle

RUN apt-get clean \
      && apt-get update \
      && apt-get install -y \
            software-properties-common \
            locales \
            ca-certificates \
            unzip \
      && update-ca-certificates \
      && locale-gen en_US en_US.UTF-8 \
      && dpkg-reconfigure locales \
      && echo "APT::Get::Assume-Yes \"true\";\nAPT::Get::force-yes \"true\";" >> /etc/apt/apt.conf.d/90forceyes

# Install java8
RUN add-apt-repository ppa:webupd8team/java \
      && apt-get update \
      && echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | debconf-set-selections \
      && apt-get install -y oracle-java8-installer

ENV JAVA_HOME /usr/lib/jvm/java-8-oracle
ENV PATH $PATH:$JAVA_HOME/bin

RUN update-alternatives --set java "$JAVA_HOME/jre/bin/java" \
      && update-alternatives --set javac "$JAVA_HOME/bin/javac" \
      && update-alternatives --set javaws "$JAVA_HOME/jre/bin/javaws"


# Setup pipeline environment
RUN apt-get update \
      # Install python
      && apt-get install -y \
            python3-pip \
            python3 \
            python3-dev \
            python3-psutil \
      && ln -s python3 /usr/bin/python \
      && ln -s pip3 /usr/bin/pip \
      && pip3 install -r https://raw.githubusercontent.com/stg-tud/MUBench/master/mubench.pipeline/requirements.txt \
      # Install runtime dependencies
      && apt-get install -y \
            ant \
            git \
            graphviz \
            maven \
            subversion \
      # Install c lib pyyaml
      && wget -q http://pyyaml.org/download/libyaml/yaml-0.1.7.tar.gz \
      && tar xvf yaml-0.1.7.tar.gz -C /usr/local \
      && rm -f yaml-0.1.7.tar.gz \
      && cd /usr/local/yaml-0.1.7 \
      && ./configure \
      && make \
      && make install \
      # Install git
      && apt-get install -y \
            git \
      && git config --global user.email "bob@builder.com" \
      &&  git config --global user.name "Bob the Builder" \
      # Install gradle
      && wget -q https://services.gradle.org/distributions/gradle-$GRADLE_VERSION-bin.zip \
      && unzip -q gradle-$GRADLE_VERSION-bin.zip -d /usr/local \
      && rm -f gradle-$GRADLE_VERSION-bin.zip \
      && ln -s /usr/local/gradle-$GRADLE_VERSION/bin/gradle /usr/bin/gradle



# Setup reviewsite environment
RUN LC_ALL=C.UTF-8 add-apt-repository -y ppa:ondrej/php \
      && apt-get update \
      && apt-get install -y \
            php7.0 \
            php7.0-xml \
            php7.0-mbstring \
            php7.0-sqlite \
            php7.0-zip \
            php7.0-curl \
      # Install composer
      && wget -q https://getcomposer.org/installer -O composer-setup.php \
      && php composer-setup.php --install-dir=/usr/local/bin --filename=composer \
      && rm composer-setup.php 

# Setup test environment
RUN \
      # Install PHPUnit
      wget -q https://phar.phpunit.de/phpunit-6.0.0.phar -O /usr/local/bin/phpunit \
      && chmod +x /usr/local/bin/phpunit \
      # Install nosetests
      && pip3 install nose \
      # Install chromeium/chromedriver
      && apt-get install -y \
            chromium-browser \
            chromium-chromedriver \
      #Install selenium
            && wget -q https://selenium-release.storage.googleapis.com/3.12/selenium-server-standalone-3.12.0.jar \
          && mv selenium-server-standalone-3.12.0.jar /usr/local/bin/selenium-server-standalone-3.12.0.jar \
          && ln /usr/lib/chromium-browser/chromedriver /usr/local/bin/chromedriver

# Cleanup
RUN apt-get clean \
      && apt-get remove build-essential \
      && apt-get autoclean \
      && apt-get autoremove

WORKDIR /mubench