FROM anapsix/alpine-java:8_jdk

LABEL maintainer="amann@st.informatik.tu-darmstadt.de"

# Install ca-certificates so that HTTPS works consistently
RUN apk update \
 && apk add ca-certificates wget \
 && update-ca-certificates \

ENV LANG=C.UTF-8 \
    GRADLE_VERSION=4.0.2 \
    GRADLE_HOME=/usr/local/gradle
ENV PATH=${PATH}:${GRADLE_HOME}/bin

# Setup pipeline environment
RUN apk update \
 \
 # Install Python
 && apk add \
      py3-psutil \
      python3 \
      yaml-dev \
 && ln -s python3 /usr/local/python \
 && ln -s pip3 /usr/local/pip \
 \
 # Install runtime dependencies
 && apk add \
      apache-ant \
      git \
      graphviz \
      maven \
      subversion \
 \
 # Install gradle
 && wget -q https://services.gradle.org/distributions/gradle-$GRADLE_VERSION-bin.zip \
 && unzip -q gradle-$GRADLE_VERSION-bin.zip -d /usr/local \
 && rm -f gradle-$GRADLE_VERSION-bin.zip \
 && ln -s /usr/local/gradle-$GRADLE_VERSION /usr/local/gradle

WORKDIR /mubench
CMD python mubench.pipeline/benchmark.py

# TODO copy only mubench.pipeline, VERSION, CRAPL-LICENSE.txt? (data, detectors, mubench(.bat))
COPY . .

RUN \
 # Install Python dependencies
 && pip install -r mubench.pipeline/requirements.txt
