FROM svamann/mubench:latest

RUN LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php
RUN apt-get update
RUN add-apt-repository -y ppa:ondrej/mysql-5.6
RUN apt-get update

RUN apt-get install php7.0
RUN apt-get install mysql-server
RUN apt-get install php7.0-xml
RUN apt-get install php7.0-mbstring
RUN apt-get install php7.0-sqlite

RUN wget https://phar.phpunit.de/phpunit.phar
RUN chmod +x phpunit.phar
RUN mv phpunit.phar /usr/local/bin/phpunit

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
RUN php composer-setup.php --install-dir=/usr/local/bin --filename=composer
RUN php -r "unlink('composer-setup.php');"
