<link rel="stylesheet" type="text/css" href="<?= htmlspecialchars($root_url); ?>style/style.css" />

<?php include "includes/menu.phtml"; ?>

    <h1>Detector: <?= htmlspecialchars($detector); ?></h1>
    <table>
        <thead>
            <tr>
                <th>Project</th>
                <th>Version</th>
                <th>Result</th>
                <th># of Findings</th>
                <th>Runtime</th>
                <th>Misuse</th>
                <?php if($exp !== "ex2") : ?><th>Violation Types</th><?php endif; ?>
                <th>Reviewed By</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach($projects as $project => $versions) : ?>
            <?php $new_project = true; ?>
            <?php foreach($versions as $version) : ?>
                <?php $new_version = true; ?>
                <?php if (!$version['hits']): ?>
                    <?php
                    $has_reviewed = $hit['reviews'] && in_array($name, $hit['reviews']);
                    $border_class = $new_project ? "top" : "";
                    ?>
                    <tr>
                        <td class="<?= $border_class ?> no-hit">
                            <?= $new_project ? htmlspecialchars($project) : ""; ?></td>
                        <td class="<?= $border_class ?> no-hit">
                            <?= $new_version ? htmlspecialchars($version['version']) : ""; ?></td>
                        <td class="<?= $border_class ?> no-hit">
                            <?= $new_version ? htmlspecialchars($version['result']) : ""; ?></td>
                        <td class="<?= $border_class ?> right no-hit">
                            <?= $new_version ? htmlspecialchars($version['number_of_findings']) : ""; ?></td>
                        <td class="<?= $border_class ?> right no-hit">
                            <?= $new_version ? htmlspecialchars(substr($version['runtime'], 0, 4)) . "s" : ""; ?></td>
                        <td class="<?= $border_class ?> no-hit"></td>
                        <?php if($exp !== "ex2") : ?>
                            <td class="<?= $border_class ?> no-hit"></td>
                        <?php endif; ?>
                        <td class="<?= $border_class ?> no-hit"></td>
                        <td class="<?= $border_class ?> no-hit"></td>
                    </tr>
                <? else: ?>
                    <?php foreach($version['hits'] as $hit) : ?>
                        <?php
                        $has_reviewed = $hit['reviews'] && in_array($name, $hit['reviews']);
                        $border_class = $new_project ? "top" : "";
                        ?>
                        <tr>
                            <td class="<?= $border_class ?>">
                                <?= $new_project ? htmlspecialchars($project) : ""; ?></td>
                            <td class="<?= $border_class ?>">
                                <?= $new_version ? htmlspecialchars($version['version']) : ""; ?></td>
                            <td class="<?= $border_class ?>">
                                <?= $new_version ? htmlspecialchars($version['result']) : ""; ?></td>
                            <td class="<?= $border_class ?> right">
                                <?= $new_version ? htmlspecialchars($version['number_of_findings']) : ""; ?></td>
                            <td class="<?= $border_class ?> right">
                                <?= $new_version ? htmlspecialchars(substr($version['runtime'], 0, 4)) . "s" : ""; ?></td>
                            <td class="<?= $border_class ?>">
                                <?= htmlspecialchars(substr($hit['misuse'], 0, strlen($project)) === $project
                                    ? substr($hit['misuse'], strlen($project) + 1) : $hit['misuse']); ?></td>
                            <?php if($exp !== "ex2") : ?>
                                <td class="<?= $border_class ?>">
                                    unknown
                                </td>
                            <?php endif; ?>
                            <?php
                                $review_url = ($logged ? htmlspecialchars($private_url) : htmlspecialchars($base_url)) . htmlspecialchars($exp) . "/" . htmlspecialchars($detector) . "/" .
                                    htmlspecialchars($hit['project']) . "/" . htmlspecialchars($hit['version']) . "/" .
                                    htmlspecialchars($hit['misuse']);
                            ?>
                            <td class="<?= $border_class ?>">
                                <?php if(array_key_exists('reviews', $hit) && $hit['reviews']) : ?>
                                    <?php foreach($hit['reviews'] as $reviewer) : ?>
                                        <a href="<?= $review_url ?>/<?= htmlspecialchars($reviewer); ?>"><?= htmlspecialchars($reviewer); ?></a>
                                    <?php endforeach; ?>
                                <?php endif; ?>
                            </td>
                            <td class="<?= $border_class ?>">
                                <?php if ($logged && $version['number_of_findings'] !== "0") : ?>
                                    <?php if (!$has_reviewed) : ?><a href="<?= $review_url; ?>" class="button">review</a><?php endif; ?>
                                <?php else : ?>
                                    <a href="<?= $review_url; ?>" class="button">view</a>
                                <?php endif; ?>
                            </td>
                        </tr>
                        <?php
                        $new_version = false;
                        $new_project = false;
                        ?>
                    <?php endforeach; ?>
                <? endif; ?>
            <?php endforeach; ?>
        <?php endforeach; ?>
        </tbody>
    </table>
