<?php
use MuBench\Decision;
use MuBench\ReviewState;
?>
<html>
<head>
    <title>MuBench :: Review Site</title>
    <link rel="stylesheet" type="text/css" href="<?= htmlspecialchars($root_url); ?>style/style.css" />
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
<?php include "includes/menu.phtml"; ?>

    <h1>Detector: <?= htmlspecialchars($detector); ?></h1>
    <table>
        <thead>
            <tr>
                <th>Project</th>
                <th>Version</th>
                <th>Result</th>
                <th># of Findings</th>
                <th>Runtime</th>
                <th>Misuse</th>
                <?php if($exp !== "ex2") : ?><th>Violation Types</th><?php endif; ?>
                <th>Decision</th>
                <th>Reviews</th>
                <th>Your Review</th>
                <th>Your Comment</th>
            </tr>
        </thead>
        <tbody>
        <?php $last_project = "" ?>
        <?php foreach($runs as $run) : ?>
            <?php
            $project = $run["project"];
            $new_project = strcmp($last_project, $run["project"]) !== 0;
            $last_project = $project;
            $version = $run["version"];
            $new_version = true;
            ?>
            <?php foreach($run['misuses'] as $misuse) : /* @var $misuse \MuBench\Misuse */ ?>
                <?php
                $classes = [];
                if($new_project) $classes[] = "top";
                if(!$misuse->hasPotentialHits()) $classes[] = "no-hit";
                $style_classes = implode(" ", $classes);
                ?>
                <tr>
                    <td class="<?= $style_classes ?>">
                        <?= $new_project ? htmlspecialchars($project) : ""; ?></td>
                    <td class="<?= $style_classes ?>">
                        <?= $new_version ? htmlspecialchars($version) : ""; ?></td>
                    <td class="<?= $style_classes ?>">
                        <?= $new_version ? htmlspecialchars($run['result']) : ""; ?></td>
                    <td class="<?= $style_classes ?> right">
                        <?= $new_version ? htmlspecialchars($run['number_of_findings']) : ""; ?></td>
                    <td class="<?= $style_classes ?> right">
                        <?= $new_version ? htmlspecialchars(substr($run['runtime'], 0, 4)) . "s" : ""; ?></td>
                    <td class="<?= $style_classes ?>">
                        <?= htmlspecialchars($misuse->getShortId()); ?></td>
                    <?php if($exp !== "ex2") : ?>
                        <td class="<?= $style_classes ?>">
                            <?= implode("<br/>", $misuse->getViolationTypes()) ?>
                        </td>
                    <?php endif; ?>
                    <?php
                        $review_url = ($logged ? htmlspecialchars($private_url) : htmlspecialchars($base_url)) . htmlspecialchars($exp) . "/" . htmlspecialchars($detector) . "/" .
                            htmlspecialchars($project) . "/" . htmlspecialchars($version) . "/" . htmlspecialchars($misuse->id);
                    ?>
                    <td class="<?= $style_classes ?>">
                        <?php $review_state = $misuse->getReviewState() ?>
                        <?php if ($review_state == ReviewState::NOTHING_TO_REVIEW): ?>
                        <?php elseif ($review_state == ReviewState::NEEDS_REVIEW): ?>
                            <i class="fa fa-search" aria-hidden="true" style="color:red;" title="Needs Review"></i>
                        <?php elseif ($review_state == ReviewState::NEEDS_CLARIFICATION): ?>
                            <i class="fa fa-question-circle" aria-hidden="true" style="color:blue;" title="Needs Clarification"></i>
                        <?php elseif ($review_state == ReviewState::DISAGREEMENT): ?>
                            <i class="fa fa-exclamation-triangle" aria-hidden="true" style="color:red;" title="Disagreement"></i>
                        <?php elseif ($review_state == ReviewState::AGREEMENT_YES): ?>
                            <i class="fa fa-thumbs-o-up" aria-hidden="true" style="color:green;" title="Agreement: Yes"></i>
                        <?php elseif ($review_state == ReviewState::AGREEMENT_NO): ?>
                            <i class="fa fa-thumbs-o-down" aria-hidden="true" style="color:darkred;" title="Agreement: No"></i>
                        <?php elseif ($review_state == ReviewState::RESOLVED_YES): ?>
                            <i class="fa fa-thumbs-o-up" aria-hidden="true" style="color:green;" title="Resolved: Yes"></i>
                            (<a href="<?= $review_url ?>/resolution"><i class="fa fa-handshake-o" aria-hidden="true" title="Resolution"></i></a>)
                        <?php elseif ($review_state == ReviewState::RESOLVED_NO): ?>
                            <i class="fa fa-thumbs-o-down" aria-hidden="true" style="color:darkred;" title="Resolved: No"></i>
                            (<a href="<?= $review_url ?>/resolution"><i class="fa fa-handshake-o" aria-hidden="true" title="Resolution"></i></a>)
                        <?php endif; ?>
                    </td>
                    <td class="<?= $style_classes ?>">
                        <ul class="inline">
                            <?php foreach($misuse->getReviews() as $review) : ?>
                                <?php $reviewer_name = htmlspecialchars($review->getReviewerName()) ?>
                                <li style="display:inline"><a href="<?= $review_url ?>/<?= $reviewer_name ?>"><?= $reviewer_name ?></a></li>
                            <?php endforeach; ?>
                        </ul>
                    </td>
                    <td class="<?= $style_classes ?>">
                        <?php
                        $button_classes = "button" . (!$misuse->hasPotentialHits() || ($logged && $misuse->hasSufficientReviews() || $misuse->hasReviewed($name)) ? " no-hit" : "")
                        ?>
                        <?php if (!$logged): ?>
                            <a href="<?= $review_url; ?>" class="<?= $button_classes ?>">view</a>
                        <?php elseif ($misuse->hasReviewed($name)): ?>
                            <a href="<?= $review_url ?>" class="<?= $button_classes ?>">edit
                            <?php $your_decision = $misuse->getReview($name)->getDecision() ?>
                            <?php if ($your_decision == Decision::YES): ?>
                                (<i class="fa fa-thumbs-o-up" aria-hidden="true" style="color:green;" title="Yes"></i>)
                            <?php elseif ($your_decision == Decision::NO): ?>
                                (<i class="fa fa-thumbs-o-down" aria-hidden="true" style="color:darkred;" title="No"></i>)
                            <?php else: ?>
                                (<i class="fa fa-question-circle" aria-hidden="true" style="color:blue;" title="Need Clarification"></i>)
                            <?php endif; ?>
                            </a>
                        <?php else: ?>
                            <a href="<?= $review_url; ?>" class="<?= $button_classes ?>">review</a>
                        <?php endif; ?>
                    </td>
                    <td class="<?= $style_classes ?>" style="max-width: 300px;">
                        <?= $misuse->hasReviewed($name) ? $misuse->getReview($name)->getComment() : "" ?>
                    </td>
                </tr>
                <?php
                $new_version = false;
                $new_project = false;
                ?>
            <?php endforeach; ?>
        <?php endforeach; ?>
        </tbody>
    </table>
</body>
</html>
