    <div>
        <?php if(!$logged) : ?>
                <a href="<?= htmlspecialchars($private_url); ?><?= htmlspecialchars($exp); ?>/<?= htmlspecialchars($detector); ?>">Login</a>
        <?php endif; ?>
        <?php if($logged) : ?>
            <a href="<?= htmlspecialchars($private_url); ?>overview">overview</a>
            <a href="<?= htmlspecialchars($private_url); ?>todo">todo</a>
        <?php endif; ?>
    </div>
    <h1>Detector: <?= htmlspecialchars($detector); ?></h1>
    <style>
        body { font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; }
        table { border-spacing: 0; }
        th { text-align: left; padding: 5px; }
        td { vertical-align: top; padding: 5px; }
        td.top { border-top: 1px solid black; }
        td.right { text-align: right; }

        a.button {
            -webkit-appearance: button;
            -moz-appearance: button;
            appearance: button;
            text-decoration: none;
            color: initial;
            padding: 2px 5px;
        }
    </style>
    <table>
        <thead>
            <tr>
                <th>Project</th>
                <th>Version</th>
                <th>Result</th>
                <th># of Findings</th>
                <th>Runtime</th>
                <th>Misuse</th>
                <?php if($exp !== "ex2") : ?><th>Violation Types</th><?php endif; ?>
                <th>Reviewed By</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php $last_project = ""; ?>
        <?php $last_version = ""; ?>
        <?php foreach($projects as $project => $versions) : ?>
            <?php foreach($versions as $version) : ?>
                <?php if (!$version['hits']): ?>
                    <tr>
                        <?php
                        $new_project = (strcmp($last_project, $project) !== 0);
                        $new_version = strcmp($last_version, $version['version']) !== 0;
                        $has_reviewed = $hit['reviews'] && in_array($name, $hit['reviews']);
                        ?>

                        <td <?php if ($new_project) : ?>class="top"<?php endif; ?>>
                            <?= $new_project ? htmlspecialchars($project) : ""; ?></td>
                        <td <?php if ($new_project) : ?>class="top"<?php endif; ?>>
                            <?= $new_version ? htmlspecialchars($version['version']) : ""; ?></td>
                        <td <?php if ($new_project) : ?>class="top"<?php endif; ?>>
                            <?= $new_version ? htmlspecialchars($version['result']) : ""; ?></td>
                        <td class="<?php if ($new_project) : ?>top<?php endif; ?> right">
                            <?= $new_version ? htmlspecialchars($version['number_of_findings']) : ""; ?></td>
                        <td class="<?php if ($new_project) : ?>top<?php endif; ?> right">
                            <?= $new_version ? htmlspecialchars(substr($version['runtime'], 0, 4)) . "s" : ""; ?></td>
                        <td <?php if ($new_project) : ?>class="top"<?php endif; ?>>
                        </td>
                        <?php if($exp !== "ex2") : ?>
                            <td <?php if ($new_project) : ?>class="top"<?php endif; ?>>
                            </td>
                        <?php endif; ?>
                        <td <?php if ($new_project) : ?>class="top"<?php endif; ?>>
                        </td>
                        <td <?php if ($new_project) : ?>class="top"<?php endif; ?>>
                        </td>
                    </tr>
                    <?php $last_version = $version['version']; ?>
                    <?php $last_project = $project; ?>
                <? else: ?>

                <?php foreach($version['hits'] as $hit) : ?>
                    <tr>
                        <?php
                        $new_project = (strcmp($last_project, $project) !== 0);
                        $new_version = strcmp($last_version, $version['version']) !== 0;
                        $has_reviewed = array_key_exists('reviews', $hit) && $hit['reviews'] && in_array($name, $hit['reviews']);
                        ?>

                        <td <?php if ($new_project) : ?>class="top"<?php endif; ?>>
                            <?= $new_project ? htmlspecialchars($project) : ""; ?></td>
                        <td <?php if ($new_project) : ?>class="top"<?php endif; ?>>
                            <?= $new_version ? htmlspecialchars($version['version']) : ""; ?></td>
                        <td <?php if ($new_project) : ?>class="top"<?php endif; ?>>
                            <?= $new_version ? htmlspecialchars($version['result']) : ""; ?></td>
                        <td class="<?php if ($new_project) : ?>top<?php endif; ?> right">
                            <?= $new_version ? htmlspecialchars($version['number_of_findings']) : ""; ?></td>
                        <td class="<?php if ($new_project) : ?>top<?php endif; ?> right">
                            <?= $new_version ? htmlspecialchars(substr($version['runtime'], 0, 4)) . "s" : ""; ?></td>
                        <td <?php if ($new_project) : ?>class="top"<?php endif; ?>>
                            <?= htmlspecialchars(substr($hit['misuse'], 0, strlen($project)) === $project
                                ? substr($hit['misuse'], strlen($project) + 1) : $hit['misuse']); ?></td>
                        <?php if($exp !== "ex2") : ?>
                            <td <?php if ($new_project) : ?>class="top"<?php endif; ?>>
                                unknown
                            </td>
                        <?php endif; ?>
                        <?php
                            $review_url = ($logged ? htmlspecialchars($private_url) : htmlspecialchars($base_url)) . htmlspecialchars($exp) . "/" . htmlspecialchars($detector) . "/" .
                                htmlspecialchars($hit['project']) . "/" . htmlspecialchars($hit['version']) . "/" .
                                htmlspecialchars($hit['misuse']);
                        ?>
                        <td <?php if ($new_project) : ?>class="top"<?php endif; ?>>
                            <?php if(array_key_exists('reviews', $hit) && $hit['reviews']) : ?>
                                <?php foreach($hit['reviews'] as $reviewer) : ?>
                                    <a href="<?= $review_url ?>/<?= htmlspecialchars($reviewer); ?>"><?= htmlspecialchars($reviewer); ?></a>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </td>
                        <td <?php if ($new_project) : ?>class="top"<?php endif; ?>>
                            <?php if ($logged && $version['number_of_findings'] !== "0") : ?>
                                <?php if (!$has_reviewed) : ?><a href="<?= $review_url; ?>" class="button">review</a><?php endif; ?>
                            <?php else : ?>
                                <a href="<?= $review_url; ?>" class="button">view</a>
                            <?php endif; ?>
                        </td>
                    </tr>
                    <?php $last_version = $version['version']; ?>
                    <?php $last_project = $project; ?>
                <?php endforeach; ?>
        <? endif; ?>
            <?php endforeach; ?>
        <?php endforeach; ?>
        </tbody>
    </table>
