<?php if(!$logged) : ?>
    <div>
        <a href="<?= htmlspecialchars($private_url); ?>">Login</a>
    </div>
<?php endif; ?>
<html>
<head>
<title>MUBench Review Page</title>
<link rel="stylesheet" type="text/css" href="<?= htmlspecialchars($root_url); ?>style/style.css" />
</head>
<body>
<h1>MUBench Review Page</h1>

<ul>
    <?php foreach($experiments as $e) : ?>
        <?php if(!$logged) : ?>
            <li><a href="<?= htmlspecialchars($base_url); ?>ex<?= htmlspecialchars($e['id']); ?>">Experiment <?= htmlspecialchars($e['id']); ?> - <?= htmlspecialchars($e['title']); ?></a></li>
        <?php endif; ?>
        <?php if($logged) : ?>
            <li><a href="<?= htmlspecialchars($private_url); ?>ex<?= htmlspecialchars($e['id']); ?>">Experiment <?= htmlspecialchars($e['id']); ?> - <?= htmlspecialchars($e['title']); ?></a></li>
        <?php endif; ?>
    <?php endforeach; ?>
</ul>

<hr style="margin-top: 2cm;"/>

<div class="comment">
<p>(this page was last updated at August 31, 2016)</p>
</div>

<div class="legal">
<a href="<?= htmlspecialchars($base_url); ?>impressum/">Legal Note / Impressum</a>
</div>
</body>
</html>
