
<html>
<head>
<title>MUBench Review Page</title>
<link rel="stylesheet" type="text/css" href="style/style.css" />
</head>
<body>
<h1>MUBench Review Page</h1>

<ul>
    <?php foreach($experiments as $e) : ?>
            <li><a href="index.php/dataset/ex<?= htmlspecialchars($e['id']); ?>">Experiment <?= htmlspecialchars($e['id']); ?> - <?= htmlspecialchars($e['title']); ?></a></li>   
    <?php endforeach; ?>
</ul>

<hr style="margin-top: 2cm;"/>

<div class="comment">
<p>(this page was last updated at August 31, 2016)</p>
</div>

<div class="legal">
<a href="index.php/impressum/">Legal Note / Impressum</a>
</div>
</body>
</html>
