<?php
$logged = true;
?>
<html>
<head>
    <link rel="stylesheet" type="text/css" href="<?= htmlspecialchars($root_url); ?>style/style.css" />
</head>
<body>
<?php include "includes/menu.phtml" ?>

<h1>My Reviews</h1>

<?php foreach($experiments as $key => $reviews) : ?>
    <h2>Experiment <?= htmlspecialchars($key); ?></h2>
<table>
    <tr>
        <th>Detector</th>
        <th>Project</th>
        <th>Version</th>
        <th>Misuse</th>
        <th>Decision</th>
        <th>Comment</th>
        <th>Types</th>
        <th>Other Reviews</th>
        <th>Actions</th>
    </tr>
    <?php
    $last_detector = "";
    $last_project = "";
    ?>
    <?php foreach($reviews as $review) : ?>
        <?php
        $new_detector = strcmp($last_detector, $review['detector']) !== 0;
        $new_project = strcmp($last_project, $review["project"]) !== 0;
        $style_classes = $new_detector || $new_project ? "class=\"top\"" : "";

        $last_detector = $review["detector"];
        $last_project = $review["project"];
        ?>
    <tr>
        <td <?= $new_detector ? $style_classes : "" ?>><?= $new_detector ? htmlspecialchars($review['detector']) : "" ?></td>
        <td <?= $style_classes ?>><?= $new_project ? htmlspecialchars($review['project']) : "" ?></td>
        <td <?= $style_classes ?>><?= htmlspecialchars($review['version']); ?></td>
        <td <?= $style_classes ?>><?= htmlspecialchars($review['misuse']); ?></td>
        <td <?= $style_classes ?>><?= htmlspecialchars($review['decision']); ?></td>
        <td <?= $style_classes ?>><?= htmlspecialchars($review['comment']); ?></td>
        <td <?= $style_classes ?>>
            <?php foreach($review['types'] as $v) : ?>
                <?= htmlspecialchars($v); ?><br/>
            <?php endforeach; ?>
        </td>
        <?php
        $review_url = htmlspecialchars($private_url) . htmlspecialchars($review['exp']) . "/" . htmlspecialchars($review['detector']) . "/" .
            htmlspecialchars($review['project']) . "/" . htmlspecialchars($review['version']) . "/" .
            htmlspecialchars($review['misuse']);
        ?>
        <td <?= $style_classes ?>>
            <?php foreach($review['reviewer'] as $reviewer) : ?>
                <?php if($reviewer !== $name): ?>
                    <a href="<?= $review_url ?>/<?= htmlspecialchars($reviewer); ?>"><?= htmlspecialchars($reviewer); ?></a>
                <?php endif; ?>
            <?php endforeach; ?>
        </td>
        <td <?= $style_classes ?>><a href="<?= $review_url ?>" class="button">edit</a></td>
    </tr>
    <?php endforeach; ?>
</table>
<?php endforeach; ?>

</body>
</html>
