<html>
<head>
    <style>
        table.fw {width:100%;}
        .vtop {vertical-align:top}
        .prettyprint ol.linenums > li { list-style-type: decimal; }
    </style>
    <script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js?autoload=true&amp;skin=sunburst"></script>
</head>
<body>
<div>
    <a href="<?= htmlspecialchars($private_url) ?>">back</a>
</div>
<h1>Review overview</h1>
<?php foreach($experiments as $key => $reviews) : ?>
    <h3>Experiment <?= htmlspecialchars($key); ?></h3>
<table border="1" cellpadding="5">
    <tr>
        <th>Detector</th>
        <th>Project</th>
        <th>Version</th>
        <th>Misuse</th>
        <th>Decision</th>
        <th>Comment</th>
        <th>Types</th>
        <th>Reviewer</th>
        <th>Review</th>
    </tr>
    <?php foreach($reviews as $review) : ?>
    <tr>
        <td><?= htmlspecialchars($review['detector']); ?></td>
        <td><?= htmlspecialchars($review['project']); ?></td>
        <td><?= htmlspecialchars($review['version']); ?></td>
        <td><?= htmlspecialchars($review['misuse']); ?></td>
        <td><?= htmlspecialchars($review['decision']); ?></td>
        <td><?= htmlspecialchars($review['comment']); ?></td>
        <td>
            <?php foreach($review['types'] as $v) : ?>
                <?= htmlspecialchars($v); ?><br/>
            <?php endforeach; ?>
        </td>
        <?php
        $review_url = htmlspecialchars($private_url) . htmlspecialchars($review['exp']) . "/" . htmlspecialchars($review['detector']) . "/" .
            htmlspecialchars($review['project']) . "/" . htmlspecialchars($review['version']) . "/" .
            htmlspecialchars($review['misuse']);
        ?>
        <td>
            <?php foreach($review['reviewer'] as $reviewer) : ?>
                <?php if($reviewer !== $name): ?>
                    <a href="<?= $review_url ?>/<?= htmlspecialchars($reviewer); ?>"><?= htmlspecialchars($reviewer); ?></a>
                <?php endif; ?>
            <?php endforeach; ?>
        </td>
        <td><a href="<?= $review_url ?>">review</a></td>
    </tr>
    <?php endforeach; ?>
</table>
<?php endforeach; ?>
<hr style="margin-top: 2cm;"/>

<div class="comment">
    <p>(this page was last updated at August 31, 2016)</p>
</div>

<div class="legal">
    <a href="/../index.php/impressum/">Legal Note / Impressum</a>
</div>
</body>
</html>
