

        <html>
            <head>
                <style>
                    table.fw {width:100%;}
                    .vtop {vertical-align:top}
                    .prettyprint ol.linenums > li { list-style-type: decimal; }
                </style>
                <script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js?autoload=true&amp;skin=sunburst"></script>
            </head>
            <body>
        <h1>Review</h1>
        <table>
            <tr><td><b>Detector:</b></td><td><?= htmlspecialchars($detector); ?></td></tr>
            <tr><td><b>Target:</b></td><td>project '<?= htmlspecialchars($project); ?>'' version <?= htmlspecialchars($version); ?></td></tr>
            <?php if($exp !== "ex2") : ?>
                <tr><td><b>Misuse:</b></td><td>misuse '<?= htmlspecialchars($misuse); ?>'</td></tr>
            <?php endif; ?>
        </table>
        <?php if($exp !== "ex2") : ?>
            <h2>Misuse Details</h2>
            <p>Details about the known misuse from the MUBench dataset.</p>
        <?php else : ?>
            <h2>Potential Misuse</h2>
            <p>Anomaly identified by the detector. Please review whether this anomaly corresponds to a misuse.</p>
        <?php endif; ?>
        <table class="fw">
        <?php if($exp !== "ex2") : ?>
            <tr><td class="vtop"><b>Description:</b></td><td><?= htmlspecialchars($desc); ?></td></tr>
            <tr><td class="vtop"><b>Fix Description:</b></td><td><?= htmlspecialchars($fix_desc); ?>(<a href="<?= htmlspecialchars($diff_url); ?>">see diff</a>)</td></tr>
            <tr><td class="vtop"><b>Violation Types:</b></td><td>
            
            <ul>
            <?php if($violation_types) : ?>
            <?php foreach($violation_types as $v) : ?>
                <li><?= htmlspecialchars($v); ?></li>
            <?php endforeach; ?>
        <?php endif; ?>
            </ul></td></tr>
        <?php else : ?>
            <tr><td><b>Finding:</b></td><td><?= htmlspecialchars($misuse); ?></td></tr>
        <?php endif; ?>
            <tr><td><b>In File:</b></td><td><?= htmlspecialchars($file); ?></td></tr>
            <tr><td><b>In Method:</b></td><td><?= htmlspecialchars($method); ?></td></tr>
            <tr>
            <?php if($exp !== "ex2") : ?>
                <td class="vtop"><b>Code with Misuse:</b></td>
            <?php else : ?>
                <td class="vtop"><b>Code with Finding:</b></td>
            <?php endif; ?>
            <td><pre class="prettyprint linenums:<?= htmlspecialchars($line); ?>"><code class="language-java"><?= htmlspecialchars($code); ?></code></pre></td></tr>
            <?php if($exp === "ex1") : ?>
                <tr><td class="vtop"><b>Pattern Code:</b></td><td><pre class="prettyprint linenums:<?= htmlspecialchars($pattern_line); ?>"><code class="language-java"><?= htmlspecialchars($pattern_code); ?></code></pre></td></tr>
            <?php endif; ?>
        </table>
        <?php if($exp !== "ex2") : ?>
            <h2>Potential Hits</h2>
            <p>Findings of the detector that identify an anomaly in the same file and method as the known misuse.</p>
        <?php else : ?>
            <h2>Metadata</h2>
        <?php endif; ?> 

        <?php if(count($hits) > 0) : ?>
        <form action="../review_form/<?= htmlspecialchars($exp); ?>_<?= htmlspecialchars($set); ?>_<?= htmlspecialchars($detector); ?>" method="post" target="">
        <table border="1" cellpadding="5">
        

        <tr>
            <th>Hit</th>
            <?php foreach($hits[0] as $key => $value) : ?>
                <?php if(is_string($key) && $key !== "target_snippets" && $key !== "file" && $key !== "line" && $key !== "project" && $key !== "version" && $key !== "misuse" && $key !== "identifier")  : ?>
                <th><?= htmlspecialchars($key); ?></th>
                <?php endif; ?>
            <?php endforeach; ?>
            <th>violation types</th>
        </tr>
    

        <?php foreach($hits as $hit) : ?>
        <tr>
            <td>
            <?php if($logged) : ?>
                <select name="review_hit[<?= htmlspecialchars($hit['id']); ?>][hit]" size="1" >
                <?php if($review && $review[$hit['id']]["hit"] === "Yes") : ?>
                    <option selected="selected" value="Yes" >Yes</option>
                <?php else : ?>
                    <option value="Yes" >?</option>
                <?php endif;?>
                <?php if($review && $review[$hit['id']]["hit"] === "No") : ?>
                    <option selected="selected" value="No" >No</option>
                <?php else : ?>
                    <option value="No" >?</option>
                <?php endif;?>

                <?php if($review && $review[$hit['id']]["hit"] === "?") : ?>
                    <option selected="selected" value="?" >?</option>
                <?php else : ?>
                    <option value="?" >?</option>
                <?php endif;?>
                </select>
            <?php else : ?>
                ?
            <?php endif;?>
            </td>
            <?php foreach($hit as $key => $value) : ?>
                <?php if(is_string($key) && $key !== "target_snippets" && $key !== "file" && $key !== "line" && $key !== "project" && $key !== "version" && $key !== "misuse" && $key !== "identifier")  : ?>
            <td>
                <?php if(!is_string($value) && is_array($value)) : ?>
                    <ul>
                        <?php foreach($value as $v) : ?>
                            <li><?= htmlspecialchars($v); ?></li>
                        <?php endforeach; ?>
                    </ul>
                <?php elseif(strpos($value, ".png") !== false) : ?>
                    <img src="/site/upload/<?= htmlspecialchars($project); ?>/<?= htmlspecialchars($version); ?>/<?= htmlspecialchars($hit[$key]); ?>" />
                <?php else : ?>
                    <?= htmlspecialchars($value); ?>
                <?php endif; ?>
             
            </td>
              <?php endif; ?>
            <?php endforeach; ?>
            <td>
                <?php if($logged) : ?>
                    <?php if($exp === "ex2") : ?>
                        <select name="review_hit[<?= htmlspecialchars($hit['id']); ?>][types][]" size="10" multiple>
                            <option value="missing/call" >missing/call</option>
                            <option value="missing/condition/null_check" >missing/condition/null_check</option>
                            <option value="missing/condition/value_or_state" >missing/condition/value_or_state</option>
                            <option value="missing/condition/synchronization" >missing/condition/synchronization</option>
                            <option value="missing/exception_handling" >missing/exception_handling</option>
                            <option value="superfluous/call" >superfluous/call</option>
                            <option value="superfluous/condition" >superfluous/condition</option>
                            <option value="superfluous/exception_handling" >superfluous/exception_handling</option>
                            <option value="misplaced/call" >misplaced/call</option>
                            <option value="missing/condition/context" >missing/condition/context</option>
                            <option value="misplaced/condition/null_check" >misplaced/condition/null_check</option>
                            <option value="misplaced/condition/value_or_state" >misplaced/condition/value_or_state</option>
                            <option value="misplaced/condition/synchronization" >misplaced/condition/synchronization</option>
                            <option value="misplaced/condition/context" >misplaced/condition/context</option>
                            <option value="superfluous/condition/null_check" >superfluous/condition/null_check</option>
                            <option value="superfluous/condition/value_or_state" >superfluous/condition/value_or_state</option>
                            <option value="superfluous/condition/synchronization" >superfluous/condition/synchronization</option>
                            <option value="superfluous/condition/context" >superfluous/condition/context</option>
                            <option value="misplaced/exception_handling" >misplaced/exception_handling</option>
                            <option value="missing/iteration" >missing/iteration</option>
                            <option value="misplaced/iteration" >misplaced/iteration</option>
                            <option value="superfluous/iteration" >superfluous/iteration</option>
                        </select>
                    <?php else : ?>
                        <?php if($violation_types) : ?>
                            <select name="review_hit[<?= htmlspecialchars($hit['id']); ?>][types][]" size="<?= htmlspecialchars(count($violation_types)); ?>" multiple>
                            <?php foreach($violation_types as $v) : ?>
                                <?php $add = true ?>
                                <?php foreach($review[$hit['id']]["types"] as $t) : ?>
                                    <?php if($t === $v) : ?>
                                        <option selected="selected" value="<?= htmlspecialchars($v); ?>"><?= htmlspecialchars($v); ?></option>
                                        <?php $add = false ?>
                                    <?php endif; ?>
                                <?php endforeach; ?>
                                <?php if($add) : ?>
                                    <option value="<?= htmlspecialchars($v); ?>"><?= htmlspecialchars($v); ?></option>
                                <?php endif; ?>
                            <?php endforeach; ?>
                            </select>
                        <?php endif;?>

                    <?php endif; ?>

                <?php else : ?>
                <ul>
                    <?php if($violation_types) : ?>
                <?php foreach($violation_types as $v) : ?>
                <li><?= htmlspecialchars($v); ?></li>
                <?php endforeach; ?>
            <?php endif;?>
                    <?php endif;?>
                </ul>
            </td>
        </tr>
       <?php endforeach; ?>
       </table>
         <?php if($logged) :?>
                <table>
                <tr><td><b>Reviewer Name:</b><br/>(lower case, no spaces)</td>
                    <td><?= htmlspecialchars($name); ?></td></tr>
                <tr><td class="vtop"><b>Comment:</b></td>

                    <td>
                    <?php if($review) : ?>
                        <textarea name="review_comment" cols="80" rows="5"><?= htmlspecialchars($review[$hits[0]['id']]['comment']); ?></textarea>
                    <?php else : ?>
                        <textarea name="review_comment" cols="80" rows="5"></textarea>
                    <?php endif; ?>
                    </td></tr>
                </table>
                <input type="hidden" name="review_name" value="<?= htmlspecialchars($name); ?>"/>
                <input type="hidden" name="review_identifier" value="<?= htmlspecialchars($exp); ?>_<?= htmlspecialchars($set); ?>_<?= htmlspecialchars($detector); ?>_<?= htmlspecialchars($project); ?>_<?= htmlspecialchars($version); ?>_<?= htmlspecialchars($misuse); ?>"/>
                    
                <input type="submit" value="Save Review" />
                </form>

        <?php endif; ?>
        <?php endif; ?>
        
            </body>
        </html>
    
