

<?php
    $columns_to_ignore = array(
        "target_snippets",
        "file",
        "method",
        "line",
        "project",
        "version",
        "misuse",
        "identifier",
        "rank",
        "exp"
    );
?>
        <html>
            <head>
                <link rel="stylesheet" type="text/css" href="<?= htmlspecialchars($root_url); ?>style/style.css" />
                <style>
                    table.fw {width:100%;}
                    .vtop {vertical-align:top}
                    .prettyprint ol.linenums > li {
                        list-style-type: decimal;
                        list-style-position: inside;
                    }
                </style>
                <script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js?autoload=true&amp;skin=sunburst"></script>
            </head>
            <body>

            <?php include "includes/menu.phtml"; ?>

        <h1>Review</h1>
        <table class="invisible">
            <tr><td><b>Detector:</b></td><td><?= htmlspecialchars($detector); ?></td></tr>
            <tr><td><b>Target:</b></td><td>project '<?= htmlspecialchars($project); ?>' version <?= htmlspecialchars($version); ?></td></tr>
            <?php if($exp !== "ex2") : ?>
                <tr><td><b>Misuse:</b></td><td>misuse '<?= htmlspecialchars($misuse); ?>'</td></tr>
            <?php endif; ?>
        </table>
        <?php if($exp !== "ex2") : ?>
            <h2>Misuse Details</h2>
            <p>Details about the known misuse from the MUBench dataset.</p>
        <?php else : ?>
            <h2>Potential Misuse</h2>
            <p>Anomaly identified by the detector. Please review whether this anomaly corresponds to a misuse.</p>
        <?php endif; ?>
        <table class="invisible fw">
        <?php if($exp !== "ex2") : ?>
            <tr><td class="vtop"><b>Description:</b></td><td><?= htmlspecialchars($desc); ?></td></tr>
            <tr><td class="vtop"><b>Fix Description:</b></td><td><?= htmlspecialchars($fix_desc); ?>(<a href="<?= htmlspecialchars($diff_url); ?>">see diff</a>)</td></tr>
            <tr><td class="vtop"><b>Violation Types:</b></td><td>
            
            <ul>
            <?php if($violation_types) : ?>
            <?php foreach($violation_types as $v) : ?>
                <li><?= htmlspecialchars($v); ?></li>
            <?php endforeach; ?>
        <?php endif; ?>
            </ul></td></tr>
        <?php else : ?>
            <tr><td><b>Finding:</b></td><td><?= htmlspecialchars($misuse); ?></td></tr>
        <?php endif; ?>
            <tr><td><b>In File:</b></td><td><?= htmlspecialchars($file); ?></td></tr>
            <tr><td><b>In Method:</b></td><td><?= htmlspecialchars($method); ?></td></tr>
            <tr>
            <?php if($exp !== "ex2") : ?>
                <td class="vtop"><b>Code with Misuse:</b></td>
            <?php else : ?>
                <td class="vtop"><b>Code with Finding:</b></td>
            <?php endif; ?>
            <td>
                <?php if($code) : ?>
                    <?php foreach($code as $c): ?>
                    <pre class="prettyprint linenums:<?= htmlspecialchars($c['line']); ?>"><code class="language-java"><?= htmlspecialchars($c['snippet']); ?></code></pre>
                    <?php endforeach; ?>
                <?php else : ?>
                    <pre>code unavailable</pre>
                <?php endif; ?>
            </td></tr>
            <?php if($exp === "ex1") : ?>
                    <tr><td class="vtop"><b>Code with Pattern(s):</b></td>
                        <td>
                <?php foreach($patterns as $pattern) : ?>
                    <pre class="prettyprint"><code class="language-java"><?= htmlspecialchars($pattern["code"]); ?></code></pre>
                <?php endforeach; ?>
                        </td></tr>
            <?php endif; ?>
        </table>
        <?php if($hits) : ?>

            <?php if($exp !== "ex2") : ?>
            <h2>Potential Hits</h2>
            <p>Findings of the detector that identify an anomaly in the same file and method as the known misuse.</p>
        <?php else : ?>
            <h2>Metadata</h2>
        <?php endif; ?> 

        <?php if(count($hits) > 0) : ?>
        <form action="<?= $private_url; ?>review/<?= htmlspecialchars($exp); ?>/<?= htmlspecialchars($detector); ?>" method="post" target="">
        <table class="potential_hits">
        

        <tr>
            <th>Hit</th>
            <th>rank</th>
            <?php foreach($hits[0] as $key => $value) : ?>
                <?php if(is_string($key) && !in_array($key, $columns_to_ignore))  : ?>
                <th><?= htmlspecialchars($key); ?></th>
                <?php endif; ?>
            <?php endforeach; ?>
            <th>violation types</th>
        </tr>
    
        <?php foreach($hits as $hit) : ?>
        <tr>
            <td>
            <?php if($logged) : ?>
                <select name="review_hit[<?= htmlspecialchars($exp === "ex2" ? $hit['misuse'] : $hit['rank']); ?>][hit]" size="1" >
                    <?php if($review && $review['hits'][$exp === "ex2" ? $hit['misuse'] : $hit['rank']]["decision"] === "No") : ?>
                        <option selected="selected" value="No" >No</option>
                    <?php else : ?>
                        <option value="No" >No</option>
                    <?php endif;?>

                    <?php if($review && $review['hits'][$exp === "ex2" ? $hit['misuse'] : $hit['rank']]["decision"] === "Yes") : ?>
                    <option selected="selected" value="Yes" >Yes</option>
                    <?php else : ?>
                    <option value="Yes" >Yes</option>
                    <?php endif;?>
                <?php if(!$review || ($review && $review['hits'][$exp === "ex2" ? $hit['misuse'] : $hit['rank']]["decision"] === "No")) : ?>
                    <option selected="selected" value="No" >No</option>
                <?php else : ?>
                    <option value="No" >No</option>
                <?php endif;?>


                    <?php if($review && $review['hits'][$exp === "ex2" ? $hit['misuse'] : $hit['rank']]["decision"] === "?") : ?>
                        <option selected="selected" value="?" >?</option>
                    <?php else : ?>
                        <option value="?" >?</option>
                    <?php endif;?>
                </select>
            <?php elseif($review) : ?>
                <?= htmlspecialchars($review['hits'][$exp === "ex2" ? $hit['misuse'] : $hit['rank']]["decision"]); ?>
            <?php elseif($name) : ?>
                No
            <?php else : ?>
                ?
            <?php endif;?>
            </td>
            <td>
                <?= htmlspecialchars($hit['rank']); ?>
            </td>
            <?php foreach($hit as $key => $value) : ?>
                <?php if(is_string($key) && !in_array($key, $columns_to_ignore))  : ?>
            <td>
                <?php if(!is_string($value) && is_array($value)) : ?>
                    <ul>
                        <?php foreach($value as $v) : ?>
                            <li><?= htmlspecialchars($v); ?></li>
                        <?php endforeach; ?>
                    </ul>
                <?php elseif(strpos($value, ".png") !== false) : ?>
                    <img src="<?= $root_url ?>upload/<?= htmlspecialchars($exp); ?>/<?= htmlspecialchars($detector); ?>/<?= htmlspecialchars($project); ?>/<?= htmlspecialchars($version); ?>/<?= htmlspecialchars($hit[$key]); ?>" />
                <?php else : ?>
                    <?= htmlspecialchars($value); ?>
                <?php endif; ?>
             
            </td>
              <?php endif; ?>
            <?php endforeach; ?>
            <td>
                    <?php if($exp === "ex2") : ?>
                    <?php if($logged) : ?>
                    <select name="review_hit[<?= htmlspecialchars($exp === "ex2" ? $hit['misuse'] : $hit['rank']); ?>][types][]" size="10" multiple>
                        <?php else : ?>
                        <select disabled name="review_hit[<?= htmlspecialchars($exp === "ex2" ? $hit['misuse'] : $hit['rank']); ?>][types][]" size="10" multiple>
                        <?php endif; ?>
                            <?php $add = true ?>
                            <?php if($review) : ?>
                            <?php foreach($review['hits'][$exp === "ex2" ? $hit['misuse'] : $hit['rank']]["types"] as $t) : ?>
                                <?php if($t === "missing/call") : ?>
                                    <option selected="selected" value="missing/call">missing/call</option>
                                    <?php $add = false ?>
                                <?php endif; ?>
                            <?php endforeach; ?>
                            <?php endif; ?>
                            <?php if($add) : ?>
                                <option value="missing/call">missing/call</option>
                            <?php endif; ?>
                            <?php $add = true ?>
                            <?php if($review) : ?>
                            <?php foreach($review['hits'][$exp === "ex2" ? $hit['misuse'] : $hit['rank']]["types"] as $t) : ?>
                                <?php if($t === "missing/condition/null_check") : ?>
                                    <option selected="selected" value="missing/condition/null_check">missing/condition/null_check</option>
                                    <?php $add = false ?>
                                <?php endif; ?>
                            <?php endforeach; ?>
                            <?php endif; ?>
                            <?php if($add) : ?>
                                <option value="missing/condition/null_check">missing/condition/null_check</option>
                            <?php endif; ?>
                            <?php $add = true ?>
                            <?php if($review) : ?>
                            <?php foreach($review['hits'][$exp === "ex2" ? $hit['misuse'] : $hit['rank']]["types"] as $t) : ?>
                                <?php if($t === "missing/condition/value_or_state") : ?>
                                    <option selected="selected" value="missing/condition/value_or_state">missing/condition/value_or_state</option>
                                    <?php $add = false ?>
                                <?php endif; ?>
                            <?php endforeach; ?>
                            <?php endif; ?>
                            <?php if($add) : ?>
                                <option value="missing/condition/value_or_state">missing/condition/value_or_state</option>
                            <?php endif; ?>
                            <?php $add = true ?>
                            <?php if($review) : ?>
                            <?php foreach($review['hits'][$exp === "ex2" ? $hit['misuse'] : $hit['rank']]["types"] as $t) : ?>
                                <?php if($t === "missing/condition/synchronization") : ?>
                                    <option selected="selected" value="missing/condition/synchronization">missing/condition/synchronization</option>
                                    <?php $add = false ?>
                                <?php endif; ?>
                            <?php endforeach; ?>
                            <?php endif; ?>
                            <?php if($add) : ?>
                                <option value="missing/condition/synchronization">missing/condition/synchronization</option>
                            <?php endif; ?>
                            <?php $add = true ?>
                            <?php if($review) : ?>
                            <?php foreach($review['hits'][$exp === "ex2" ? $hit['misuse'] : $hit['rank']]["types"] as $t) : ?>
                                <?php if($t === "missing/exception_handling") : ?>
                                    <option selected="selected" value="missing/exception_handling">missing/exception_handling</option>
                                    <?php $add = false ?>
                                <?php endif; ?>
                            <?php endforeach; ?>
                            <?php endif; ?>
                            <?php if($add) : ?>
                                <option value="missing/exception_handling">missing/exception_handling</option>
                            <?php endif; ?>
                            <?php $add = true ?>
                            <?php if($review) : ?>
                            <?php foreach($review['hits'][$exp === "ex2" ? $hit['misuse'] : $hit['rank']]["types"] as $t) : ?>
                                <?php if($t === "superfluous/call") : ?>
                                    <option selected="selected" value="superfluous/call">superfluous/call</option>
                                    <?php $add = false ?>
                                <?php endif; ?>
                            <?php endforeach; ?>
                            <?php endif; ?>
                            <?php if($add) : ?>
                                <option value="superfluous/call">superfluous/call</option>
                            <?php endif; ?>
                            <?php $add = true ?>
                            <?php if($review) : ?>
                            <?php foreach($review['hits'][$exp === "ex2" ? $hit['misuse'] : $hit['rank']]["types"] as $t) : ?>
                                <?php if($t === "superfluous/condition") : ?>
                                    <option selected="selected" value="superfluous/condition">superfluous/condition</option>
                                    <?php $add = false ?>
                                <?php endif; ?>
                            <?php endforeach; ?>
                            <?php endif; ?>
                            <?php if($add) : ?>
                                <option value="superfluous/condition">superfluous/condition</option>
                            <?php endif; ?>
                            <?php $add = true ?>
                            <?php if($review) : ?>
                            <?php foreach($review['hits'][$exp === "ex2" ? $hit['misuse'] : $hit['rank']]["types"] as $t) : ?>
                                <?php if($t === "superfluous/exception_handling") : ?>
                                    <option selected="selected" value="superfluous/exception_handling">superfluous/exception_handling</option>
                                    <?php $add = false ?>
                                <?php endif; ?>
                            <?php endforeach; ?>
                            <?php endif; ?>
                            <?php if($add) : ?>
                                <option value="superfluous/exception_handling">superfluous/exception_handling</option>
                            <?php endif; ?>
                            <?php $add = true ?>
                            <?php if($review) : ?>
                            <?php foreach($review['hits'][$exp === "ex2" ? $hit['misuse'] : $hit['rank']]["types"] as $t) : ?>
                                <?php if($t === "misplaced/call") : ?>
                                    <option selected="selected" value="misplaced/call">misplaced/call</option>
                                    <?php $add = false ?>
                                <?php endif; ?>
                            <?php endforeach; ?>
                            <?php endif; ?>
                            <?php if($add) : ?>
                                <option value="misplaced/call">misplaced/call</option>
                            <?php endif; ?>
                            <?php $add = true ?>
                            <?php if($review) : ?>
                            <?php foreach($review['hits'][$exp === "ex2" ? $hit['misuse'] : $hit['rank']]["types"] as $t) : ?>
                                <?php if($t === "missing/condition/context") : ?>
                                    <option selected="selected" value="missing/condition/context">missing/condition/context</option>
                                    <?php $add = false ?>
                                <?php endif; ?>
                            <?php endforeach; ?>
                            <?php endif; ?>
                            <?php if($add) : ?>
                                <option value="missing/condition/context">missing/condition/context</option>
                            <?php endif; ?>
                            <?php $add = true ?>
                            <?php if($review) : ?>
                            <?php foreach($review['hits'][$exp === "ex2" ? $hit['misuse'] : $hit['rank']]["types"] as $t) : ?>
                                <?php if($t === "misplaced/condition/null_check") : ?>
                                    <option selected="selected" value="misplaced/condition/null_check">misplaced/condition/null_check</option>
                                    <?php $add = false ?>
                                <?php endif; ?>
                            <?php endforeach; ?>
                            <?php endif; ?>
                            <?php if($add) : ?>
                                <option value="misplaced/condition/null_check">misplaced/condition/null_check</option>
                            <?php endif; ?>
                            <?php $add = true ?>
                            <?php if($review) : ?>
                            <?php foreach($review['hits'][$exp === "ex2" ? $hit['misuse'] : $hit['rank']]["types"] as $t) : ?>
                                <?php if($t === "misplaced/condition/value_or_state") : ?>
                                    <option selected="selected" value="misplaced/condition/value_or_state">misplaced/condition/value_or_state</option>
                                    <?php $add = false ?>
                                <?php endif; ?>
                            <?php endforeach; ?>
                            <?php endif; ?>
                            <?php if($add) : ?>
                                <option value="misplaced/condition/value_or_state">misplaced/condition/value_or_state</option>
                            <?php endif; ?>
                            <?php $add = true ?>
                            <?php if($review) : ?>
                            <?php foreach($review['hits'][$exp === "ex2" ? $hit['misuse'] : $hit['rank']]["types"] as $t) : ?>
                                <?php if($t === "misplaced/condition/synchronization") : ?>
                                    <option selected="selected" value="misplaced/condition/synchronization">misplaced/condition/synchronization</option>
                                    <?php $add = false ?>
                                <?php endif; ?>
                            <?php endforeach; ?>
                            <?php endif; ?>
                            <?php if($add) : ?>
                                <option value="misplaced/condition/synchronization">misplaced/condition/synchronization</option>
                            <?php endif; ?>
                            <?php $add = true ?>
                            <?php if($review) : ?>
                            <?php foreach($review['hits'][$exp === "ex2" ? $hit['misuse'] : $hit['rank']]["types"] as $t) : ?>
                                <?php if($t === "misplaced/condition/context") : ?>
                                    <option selected="selected" value="misplaced/condition/context">misplaced/condition/context</option>
                                    <?php $add = false ?>
                                <?php endif; ?>
                            <?php endforeach; ?>
                            <?php endif; ?>
                            <?php if($add) : ?>
                                <option value="misplaced/condition/context">misplaced/condition/context</option>
                            <?php endif; ?>
                            <?php $add = true ?>
                            <?php if($review) : ?>
                            <?php foreach($review['hits'][$exp === "ex2" ? $hit['misuse'] : $hit['rank']]["types"] as $t) : ?>
                                <?php if($t === "superfluous/condition/null_check") : ?>
                                    <option selected="selected" value="superfluous/condition/null_check">superfluous/condition/null_check</option>
                                    <?php $add = false ?>
                                <?php endif; ?>
                            <?php endforeach; ?>
                            <?php endif; ?>
                            <?php if($add) : ?>
                                <option value="superfluous/condition/null_check">superfluous/condition/null_check</option>
                            <?php endif; ?>
                            <?php $add = true ?>
                            <?php if($review) : ?>
                            <?php foreach($review['hits'][$exp === "ex2" ? $hit['misuse'] : $hit['rank']]["types"] as $t) : ?>
                                <?php if($t === "superfluous/condition/value_or_state") : ?>
                                    <option selected="selected" value="superfluous/condition/value_or_state">superfluous/condition/value_or_state</option>
                                    <?php $add = false ?>
                                <?php endif; ?>
                            <?php endforeach; ?>
                            <?php endif; ?>
                            <?php if($add) : ?>
                                <option value="superfluous/condition/value_or_state">superfluous/condition/value_or_state</option>
                            <?php endif; ?>
                            <?php $add = true ?>
                            <?php if($review) : ?>
                            <?php foreach($review['hits'][$exp === "ex2" ? $hit['misuse'] : $hit['rank']]["types"] as $t) : ?>
                                <?php if($t === "superfluous/condition/synchronization") : ?>
                                    <option selected="selected" value="superfluous/condition/synchronization">superfluous/condition/synchronization</option>
                                    <?php $add = false ?>
                                <?php endif; ?>
                            <?php endforeach; ?>
                            <?php endif; ?>
                            <?php if($add) : ?>
                                <option value="superfluous/condition/synchronization">superfluous/condition/synchronization</option>
                            <?php endif; ?>
                            <?php $add = true ?>
                            <?php if($review) : ?>
                            <?php foreach($review['hits'][$exp === "ex2" ? $hit['misuse'] : $hit['rank']]["types"] as $t) : ?>
                                <?php if($t === "superfluous/condition/context") : ?>
                                    <option selected="selected" value="superfluous/condition/context">superfluous/condition/context</option>
                                    <?php $add = false ?>
                                <?php endif; ?>
                            <?php endforeach; ?>
                            <?php endif; ?>
                            <?php if($add) : ?>
                                <option value="superfluous/condition/context">superfluous/condition/context</option>
                            <?php endif; ?>
                            <?php $add = true ?>
                            <?php if($review) : ?>
                            <?php foreach($review['hits'][$exp === "ex2" ? $hit['misuse'] : $hit['rank']]["types"] as $t) : ?>
                                <?php if($t === "misplaced/exception_handling") : ?>
                                    <option selected="selected" value="misplaced/exception_handling">misplaced/exception_handling</option>
                                    <?php $add = false ?>
                                <?php endif; ?>
                            <?php endforeach; ?>
                            <?php endif; ?>
                            <?php if($add) : ?>
                                <option value="misplaced/exception_handling">misplaced/exception_handling</option>
                            <?php endif; ?>
                            <?php $add = true ?>
                            <?php if($review) : ?>
                            <?php foreach($review['hits'][$exp === "ex2" ? $hit['misuse'] : $hit['rank']]["types"] as $t) : ?>
                                <?php if($t === "missing/iteration") : ?>
                                    <option selected="selected" value="missing/iteration">missing/iteration</option>
                                    <?php $add = false ?>
                                <?php endif; ?>
                            <?php endforeach; ?>
                            <?php endif; ?>
                            <?php if($add) : ?>
                                <option value="missing/iteration">missing/iteration</option>
                            <?php endif; ?>
                            <?php $add = true ?>
                            <?php if($review) : ?>
                            <?php foreach($review['hits'][$exp === "ex2" ? $hit['misuse'] : $hit['rank']]["types"] as $t) : ?>
                                <?php if($t === "misplaced/iteration") : ?>
                                    <option selected="selected" value="misplaced/iteration">misplaced/iteration</option>
                                    <?php $add = false ?>
                                <?php endif; ?>
                            <?php endforeach; ?>
                            <?php endif; ?>
                            <?php if($add) : ?>
                                <option value="misplaced/iteration">misplaced/iteration</option>
                            <?php endif; ?>
                            <?php $add = true ?>
                            <?php if($review) : ?>
                            <?php foreach($review['hits'][$exp === "ex2" ? $hit['misuse'] : $hit['rank']]["types"] as $t) : ?>
                                <?php if($t === "superfluous/iteration") : ?>
                                    <option selected="selected" value="superfluous/iteration">superfluous/iteration</option>
                                    <?php $add = false ?>
                                <?php endif; ?>
                            <?php endforeach; ?>
                            <?php endif; ?>
                            <?php if($add) : ?>
                                <option value="superfluous/iteration">superfluous/iteration</option>
                            <?php endif; ?>
                        </select>
                    <?php else : ?>
                        <?php if($violation_types) : ?>
                            <?php if($logged) : ?>
                        <select name="review_hit[<?= htmlspecialchars($exp === "ex2" ? $hit['misuse'] : $hit['rank']); ?>][types][]" size="<?= htmlspecialchars(count($violation_types)); ?>" multiple>
                        <?php else : ?>
                                <select disabled name="review_hit[<?= htmlspecialchars($hit['id']); ?>][types][]" size="<?= htmlspecialchars(count($violation_types)); ?>" multiple>
                            <?php endif; ?>
                                <?php foreach($violation_types as $v) : ?>
                                <?php $add = true ?>
                                    <?php if($review) : ?>
                                <?php foreach($review['hits'][$exp === "ex2" ? $hit['misuse'] : $hit['rank']]["types"] as $t) : ?>
                                    <?php if($t === $v) : ?>
                                        <option selected="selected" value="<?= htmlspecialchars($v); ?>"><?= htmlspecialchars($v); ?></option>
                                        <?php $add = false ?>
                                    <?php endif; ?>
                                <?php endforeach; ?>
                                    <?php endif; ?>
                                <?php if($add) : ?>
                                    <option value="<?= htmlspecialchars($v); ?>"><?= htmlspecialchars($v); ?></option>
                                <?php endif; ?>
                            <?php endforeach; ?>
                            </select>
                        <?php endif;?>

                    <?php endif; ?>
            </td>
        </tr>
       <?php endforeach; ?>
       </table>
         <?php if($logged) :?>
                <table class="invisible">
                <tr><td><b>Reviewer Name:</b></td>
                    <td><?= htmlspecialchars($name); ?></td></tr>
                <tr><td class="vtop"><b>Comment:</b></td>

                    <td>
                    <?php if($review) : ?>
                        <textarea name="review_comment" cols="80" rows="5"><?= htmlspecialchars($review['comment']); ?></textarea>
                    <?php else : ?>
                        <textarea name="review_comment" cols="80" rows="5"></textarea>
                    <?php endif; ?>
                    </td></tr>
                </table>
                <input type="hidden" name="review_name" value="<?= htmlspecialchars($name); ?>"/>
                <input type="hidden" name="review_exp" value="<?= htmlspecialchars($exp); ?>">
                <input type="hidden" name="review_detector" value="<?= htmlspecialchars($detector); ?>">
                <input type="hidden" name="review_project" value="<?= htmlspecialchars($project); ?>">
                <input type="hidden" name="review_version" value="<?= htmlspecialchars($version); ?>">
                <input type="hidden" name="review_misuse" value="<?= htmlspecialchars($misuse); ?>">
                <input type="submit" value="Save Review" />
                </form>

        <?php endif; ?>
        <?php if($review && !$logged) :?>
                <table class="invisible">
                    <tr><td><b>Reviewer Name:</b></td>
                        <td><?= htmlspecialchars($name); ?></td></tr>
                    <tr><td class="vtop"><b>Comment:</b></td>
                        <td>
                                <textarea disabled name="review_comment" cols="80" rows="5"><?= htmlspecialchars($review['comment']); ?></textarea>
                        </td></tr>
                </table>
        <?php endif; ?>
        <?php endif; ?>
        <?php endif; ?>
            </body>
        </html>
    
