

        <html>
            <head>
                <style>
                    table.fw {width:100%;}
                    .vtop {vertical-align:top}
                    .prettyprint ol.linenums > li { list-style-type: decimal; }
                </style>
                <script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js?autoload=true&amp;skin=sunburst"></script>
            </head>
            <body>
            
        <h1>Review</h1>
        <table>
            <tr><td><b>Detector:</b></td><td><?= htmlspecialchars($detector); ?></td></tr>
            <tr><td><b>Target:</b></td><td>project '<?= htmlspecialchars($project); ?>'' version <?= htmlspecialchars($version); ?></td></tr>
            <tr><td><b>Misuse:</b></td><td>misuse '<?= htmlspecialchars($misuse); ?>'</td></tr>
        </table>
        <h2>Misuse Details</h2>
        <p>Details about the known misuse from the MUBench dataset.</p>
        <table class="fw">
            <tr><td class="vtop"><b>Description:</b></td><td><?= htmlspecialchars($desc); ?></td></tr>
            <tr><td class="vtop"><b>Fix Description:</b></td><td><?= htmlspecialchars($fix_desc); ?>(<a href="<?= htmlspecialchars($diff_url); ?>">see diff</a>)</td></tr>
            <tr><td class="vtop"><b>Violation Types:</b></td><td>
            
            <ul>
            <?php foreach($violation_types as $v) : ?>
                <li><?= htmlspecialchars($v); ?></li>
            <?php endforeach; ?>
            </ul></td></tr>
            <tr><td><b>In File:</b></td><td><?= htmlspecialchars($file); ?></td></tr>
            <tr><td><b>In Method:</b></td><td><?= htmlspecialchars($method); ?></td></tr>
            <tr><td class="vtop"><b>Code with Misuse:</b></td><td><pre class="prettyprint linenums:<?= htmlspecialchars($line); ?>"><code class="language-java"><?= htmlspecialchars($code); ?></code></pre></td></tr>
            <tr><td class="vtop"><b>Pattern Code:</b></td><td><pre class="prettyprint linenums:<?= htmlspecialchars($pattern_line); ?>"><code class="language-java"><?= htmlspecialchars($pattern_code); ?></code></pre></td></tr>
        </table>
        <h2>Potential Hits</h2>
        <p>Findings of the detector that identify an anomaly in the same file and method as the known misuse.</p>
        <?php if(count($hits) > 0) : ?>
        <table border="1" cellpadding="5">
        <tr>
            <th>Hit</th>
            <th>id</th>
            <th>confidence</th>
            <th>rank</th>
            <th>environment</th>
            <th>pattern</th>
            <th>Violation Type</th>
        </tr>
        <?php foreach($hits as $hit) : ?>
        <tr>
            <td>?
            </td>
            <td>
                <?= htmlspecialchars($hit['id']); ?>
            </td>
            <td>
                <?= htmlspecialchars($hit['confidence']); ?>
            </td>
            <td>
                <?= htmlspecialchars($hit['rank']); ?>
            </td>
            <td>
            <img src="/upload/<?= htmlspecialchars($project); ?>/<?= htmlspecialchars($version); ?>/<?= htmlspecialchars($hit['target_environment_mapping']); ?>" />
            </td>
            <td>
            <img src="/upload/<?= htmlspecialchars($project); ?>/<?= htmlspecialchars($version); ?>/<?= htmlspecialchars($hit['pattern_violation']); ?>" />
            </td>
            <td>
                <ul>
                <?php foreach($violation_types as $v) : ?>
                    <li><?= htmlspecialchars($v); ?></li>
                <?php endforeach; ?>
                </ul>
            </td>
        </tr>
       <?php endforeach; ?>
       </table>
        <?php endif; ?>
            </body>
        </html>
    
