

        <html>
            <head>
                <style>
                    table.fw {width:100%;}
                    .vtop {vertical-align:top}
                    .prettyprint ol.linenums > li { list-style-type: decimal; }
                </style>
                <script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js?autoload=true&amp;skin=sunburst"></script>
            </head>
            <body>
            
        <h1>Review</h1>
        <table>
            <tr><td><b>Detector:</b></td><td>mudetect-do</td></tr>
            <tr><td><b>Target:</b></td><td>project 'aclang' version 587</td></tr>
            <tr><td><b>Misuse:</b></td><td>misuse 'aclang.1'</td></tr>
        </table>
        <h2>Misuse Details</h2>
        <p>Details about the known misuse from the MUBench dataset.</p>
        <table class="fw">
            <tr><td class="vtop"><b>Description:</b></td><td>StrBuilder.getNullText() may return null.</td></tr>
            <tr><td class="vtop"><b>Fix Description:</b></td><td>Check for null before using. (<a href="http://svn.apache.org/viewvc/commons/proper/lang/trunk/src/java/org/apache/commons/lang/text/StrBuilder.java?r1=627248&r2=627247&pathrev=627248&diff_format=h">see diff</a>)</td></tr>
            <tr><td class="vtop"><b>Violation Types:</b></td><td><ul>
                <li>missing/condition/null_check</li>
            </ul></td></tr>
            <tr><td><b>In File:</b></td><td>org/apache/commons/lang/text/StrBuilder.java</td></tr>
            <tr><td><b>In Method:</b></td><td>appendFixedWidthPadLeft(Object, int, char)</td></tr>
            <tr><td class="vtop"><b>Code with Misuse:</b></td><td><pre class="prettyprint linenums:1170"><code class="language-java">class StrBuilder {
    /**
     * Appends an object to the builder padding on the left to a fixed width.
     * The &lt;code&gt;toString&lt;/code&gt; of the object is used.
     * If the object is larger than the length, the left hand side is lost.
     * If the object is null, the null text value is used.
     * 
     * @param obj  the object to append, null uses null text
     * @param width  the fixed field width, zero or negative has no effect
     * @param padChar  the pad character to use
     * @return this, to enable chaining
     */
    public StrBuilder appendFixedWidthPadLeft(Object obj, int width, char padChar) {
        if (width &gt; 0) {
            ensureCapacity(size + width);
            String str = (obj == null ? getNullText() : obj.toString());
            int strLen = str.length();
            if (strLen &gt;= width) {
                str.getChars(strLen - width, strLen, buffer, size);
            } else {
                int padLen = width - strLen;
                for (int i = 0; i &lt; padLen; i++) {
                    buffer[size + i] = padChar;
                }
                str.getChars(0, strLen, buffer, size + padLen);
            }
            size += width;
        }
        return this;
    }
}</code></pre></td></tr>
            <tr><td class="vtop"><b>Pattern Code:</b></td><td><pre class="prettyprint linenums:1"><code class="language-java">class NullTextNull extends StrBuilder {
  String pattern(Object obj) {
    String str = (obj == null ? this.getNullText() : obj.toString());
    if (str == null) {
      str = &quot;&quot;;
    }
    return str;
  }
}</code></pre></td></tr>
        </table>
        <h2>Potential Hits</h2>
        <p>Findings of the detector that identify an anomaly in the same file and method as the known misuse.
            Please reviews whether any of these findings actually correspond to the kown misuse.</p>
                <form action="../../../../../review_submission_receiver.php" method="post" target="review_submission_target">
            <table border="1" cellpadding="5">
        <tr><th>Hit</th><th>id</th><th>_psup</th><th>_psup2</th><th>_pvs</th><th>_vsup</th><th>confidence</th><th>missing_edges</th><th>missing_nodes</th><th>overlap</th><th>pattern</th><th>reduced_target</th><th>Violation Type</tr>
        <tr>
            <td><select name="findings[6][assessment]" size="1" ><option value="No" >No</option>
<option value="Yes" >Yes</option>
<option value="?" >?</option>
</select></td>
            <td>6</td><td>0</td><td>0</td><td>5</td><td>1</td><td>-5.0</td><td><ul>
                <li>== -(cond)-&gt; =</li>
                <li>NullTextNull0.getNullText() -(para)-&gt; ==</li>
                <li>NullTextNull0.getNullText() -(def)-&gt; String</li>
                <li>NullTextNull0.getNullText() -(para)-&gt; return</li>
                <li>Object.toString() -(para)-&gt; ==</li>
                <li>Object.toString() -(para)-&gt; return</li>
                <li>null(null) -(para)-&gt; ==</li>
                <li>NullTextNull0 -(recv)-&gt; NullTextNull0.getNullText()</li>
                <li>String -(para)-&gt; ==</li>
                <li>String -(para)-&gt; return</li>
                <li>String() -(para)-&gt; =</li>
                <li>== -(cond)-&gt; NullTextNull0.getNullText()</li>
            </ul></td><td><ul>
                <li>NullTextNull0.getNullText()</li>
                <li>null(null)</li>
                <li>NullTextNull0</li>
                <li>String</li>
                <li>String()</li>
                <li>return</li>
                <li>==</li>
                <li>&#x27;=&#x27;</li>
            </ul></td><td><img src="./f6-overlap.png" /></td><td><img src="./f6-pattern.png" /></td><td><img src="./f6-reduced_target.png" /></td>
            <td><select name="findings[6][violations][]" size="1" multiple><option value="missing/condition/null_check" >missing/condition/null_check</option>
</select></td>
        </tr>
<tr>
            <td><select name="findings[9][assessment]" size="1" ><option value="No" >No</option>
<option value="Yes" >Yes</option>
<option value="?" >?</option>
</select></td>
            <td>9</td><td>0</td><td>0</td><td>5</td><td>1</td><td>-5.0</td><td><ul>
                <li>== -(cond)-&gt; NullTextNull0.getNullText()</li>
                <li>Object -(para)-&gt; ==</li>
                <li>Object -(recv)-&gt; Object.toString()</li>
                <li>String() -(para)-&gt; =</li>
                <li>NullTextNull0.getNullText() -(para)-&gt; ==</li>
                <li>NullTextNull0.getNullText() -(para)-&gt; return</li>
                <li>NullTextNull0 -(recv)-&gt; NullTextNull0.getNullText()</li>
                <li>== -(cond)-&gt; =</li>
                <li>null(null) -(para)-&gt; ==</li>
                <li>Object.toString() -(para)-&gt; ==</li>
                <li>Object.toString() -(para)-&gt; return</li>
            </ul></td><td><ul>
                <li>Object</li>
                <li>String()</li>
                <li>NullTextNull0.getNullText()</li>
                <li>NullTextNull0</li>
                <li>==</li>
                <li>null(null)</li>
                <li>&#x27;=&#x27;</li>
                <li>return</li>
            </ul></td><td><img src="./f9-overlap.png" /></td><td><img src="./f9-pattern.png" /></td><td><img src="./f9-reduced_target.png" /></td>
            <td><select name="findings[9][violations][]" size="1" multiple><option value="missing/condition/null_check" >missing/condition/null_check</option>
</select></td>
        </tr>
        </table>
        
            <br/>
            <table>
                <tr><td><b>Reviewer Name:</b><br/>(lower case, no spaces)</td>
                    <td><input type="text" name="reviewer_name" pattern="[a-z]+" size="30" value="" /></td></tr>
                <tr><td class="vtop"><b>Comment:</b></td>
                    <td><textarea name="reviewer_comment" cols="120" rows="8"></textarea></td></tr>
            </table>
            <iframe name="review_submission_target" width="100%" height="100px" style="border-style:none"></iframe>
            <input type="hidden" name="review_name[]" value="ex1_detect-only"/>
            <input type="hidden" name="review_name[]" value="mudetect-do"/>
            <input type="hidden" name="review_name[]" value="aclang"/>
            <input type="hidden" name="review_name[]" value="587"/>
            <input type="hidden" name="review_name[]" value="aclang.1"/>
            <input type="hidden" name="review_name[]" value="review"/>
            <input type="submit" value="Save Review"/>
        </form>
        
            </body>
        </html>
    
