<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="<?= htmlspecialchars($root_url); ?>style/style.css" />
    <meta charset="UTF-8">

</head>
<body>
    <?php foreach($experiments as $key => $reviews) : ?>
        <h2>Experiment <?= htmlspecialchars($key); ?></h2>
        <table style="width: 600px;">
            <tr>
                <th>Detector</th>
                <th>Project</th>
                <th>Version</th>
                <th>Misuse</th>
                <th>Reviewer</th>
                <th>Status</th>
            </tr>
            <?php foreach($reviews as $review) : ?>
                <tr>
                    <td><?= htmlspecialchars($review['detector']); ?></td>
                    <td><?= htmlspecialchars($review['project']); ?></td>
                    <td><?= htmlspecialchars($review['version']); ?></td>
                    <td><?= htmlspecialchars($review['misuse']); ?></td>
                    <?php
                    $review_url = htmlspecialchars($private_url) . htmlspecialchars($review['exp']) . "/" . htmlspecialchars($review['detector']) . "/" .
                        htmlspecialchars($review['project']) . "/" . htmlspecialchars($review['version']) . "/" .
                        htmlspecialchars($review['misuse']);
                    ?>
                    <td>
                        <?php foreach($review['reviewer'] as $reviewer) : ?>
                            <a href="<?= $review_url ?>/<?= htmlspecialchars($reviewer); ?>"><?= htmlspecialchars($reviewer); ?></a>
                        <?php endforeach; ?>
                    </td>
                    <td style="background-color:<?= htmlspecialchars($review['status']) === "decided" ? "green" : (htmlspecialchars($review['status']) === "conflict" ? "red" : "yellow"); ?>"><?= htmlspecialchars($review['decision']); ?></td>
                </tr>
            <?php endforeach; ?>
        </table>
    <?php endforeach; ?>
</body>
</html>