<html>
<head>
    <style>
        table.fw {width:100%;}
        .vtop {vertical-align:top}
        .prettyprint ol.linenums > li { list-style-type: decimal; }
    </style>
    <script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js?autoload=true&amp;skin=sunburst"></script>
</head>
<body>
<h1>Review todo</h1>
<?php foreach($experiments as $key => $reviews) : ?>
    <h3>Experiment <?= htmlspecialchars($key); ?></h3>
    <table border="1" cellpadding="5">
        <tr>
            <th>Dataset</th>
            <th>Detector</th>
            <th>Project</th>
            <th>Version</th>
            <th>Misuse</th>
            <th>Review</th>
        </tr>
        <?php foreach($reviews as $review) : ?>
            <tr>
                <td><?= htmlspecialchars($review['dataset']); ?></td>
                <td><?= htmlspecialchars($review['detector']); ?></td>
                <td><?= htmlspecialchars($review['project']); ?></td>
                <td><?= htmlspecialchars($review['version']); ?></td>
                <td><?= htmlspecialchars($review['misuse']); ?></td>
                <td><a href="./<?= htmlspecialchars($review['exp']); ?>/<?= htmlspecialchars($review['dataset']); ?>/<?= htmlspecialchars($review['detector']); ?>/<?= htmlspecialchars($review['project']); ?>/<?= htmlspecialchars($review['version']); ?>/<?= htmlspecialchars($review['misuse']); ?>">review</a></td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php endforeach; ?>
<hr style="margin-top: 2cm;"/>

<div class="comment">
    <p>(this page was last updated at August 31, 2016)</p>
</div>

<div class="legal">
    <a href="/../index.php/impressum/">Legal Note / Impressum</a>
</div>
</body>
</html>
